module.exports = {
  compliments: [
    "Good vibes: loved the spicy chicken sandwich and it felt like a smooth visit.",
    "No cap, that sandwich was fresh.",
    "Good vibes: henry greeted me and made it simple.",
    "On this visit, Henry stayed calm and kept the rush smooth.",
    "Just saying, happy with how dine in was quick and it was a pleasant visit.",
    "Just saying, drive thru moved fast even with a long line.",
    "Overall, rush was heavy but they didnt miss a thing.",
    "All in all, The nuggets were crisp and they kept things moving.",
    "Good vibes: They brought my order to the table and they kept things moving.",
    "Quick shoutout: I noticed counter service was smooth.",
    "Just saying, Chicken was hot and fresh.",
    "For real, the drive thru was clutch today.",
    "Overall, Big thanks again yall that was fast.",
    "This time, the meal was hot and came out right.",
    "Quick shoutout: the counter staff were upbeat and helpful.",
    "All in all, The batter was crispy without being greasy.",
    "Today, The dining room lights were bright and the team stayed organized.",
    "Just saying, good spice level and the food was hot when i got it.",
    "Lowkey, a smooth drive thru.",
    "Today, the sweet tea was just right.",
    "Good vibes: Great value for a filling meal and the team kept it welcoming.",
    "Just saying, The gravy was smooth and warm.",
    "For real, The gloves were used properly and the team stayed organized.",
    "All in all, The staff stayed calm during a rush and it made the stop easy.",
    "Overall, Food was packed well and everything came out right.",
    "All in all, they separated my kids meal from the spicy food.",
    "All in all, they kept the line moving even with a big order ahead.",
    "Just saying, The spicy sandwich had a great kick.",
    "All in all, The rice was not dry and they kept things moving.",
    "This time, Alexandar checked the lobby and said hi.",
    "Overall, Pickup was ready when i got there and it made the stop easy.",
    "Today, Order was right and it felt easy from start to finish.",
    "Good vibes: the staff asked if i needed anything else.",
    "Quick shoutout: Happy with how the drive thru window service was quick.",
    "Honestly, Drive thru staff were friendly and everything came out right.",
    "Just saying, the food was fire and fresh.",
    "Good vibes: real quick stop and no stress.",
    "All in all, Solid visit and it made the stop easy.",
    "On this visit, grabbed a quick bite before practice and it was on time.",
    "Just saying, the drink tasted fresh and not flat.",
    "For real, brought the kids and the staff were patient and kind.",
    "Honestly, Dine in service was fast and the pace stayed steady.",
    "For real, the coleslaw was crisp and fresh.",
    "Honestly, alexander checked the lobby and kept it tidy.",
    "Honestly, the dining room felt calm even with a few people.",
    "Just saying, The food smelled fresh and appetizing.",
    "Overall, Service was fast even during busy time and it made the stop easy.",
    "Yall, kept it moving even with the rush.",
    "Good vibes: ordered for a group and they kept it organized.",
    "Honestly, vibes were calm and the order was right.",
    "All in all, the staff smiled and said have a good day.",
    "Overall, the crew was on point fr.",
    "This time, red beans and rice were good.",
    "For real, Food quality was good and it made the stop easy.",
    "On this visit, they kept the music low and it felt relaxed.",
    "Honestly, busy hour but they still got my order out fast.",
    "Good vibes: they honored my extra sauce request and it felt like a smooth visit.",
    "This time, i noticed the meal was satisfying and hearty.",
    "This time, The sandwich wrapper was clean and neat.",
    "Just saying, the floor was dry and not slippery.",
    "For real, good energy from the crew today.",
    "On this visit, the cup was filled properly and it felt like a smooth visit.",
    "Quick shoutout: i noticed dine in was clean and it made the stop easy.",
    "Today, drive thru was backed up but the wait wasnt bad.",
    "Just saying, the cashier thanked me for coming in.",
    "Honestly, Glad to see the drive thru staff were friendly.",
    "On this visit, Got my food quick in the drive thru.",
    "Good vibes: trash bins were not overflowing in the dining room.",
    "This time, The dining room was comfortable and they kept things moving.",
    "Honestly, the lobby was cool and comfortable.",
    "Today, Portions felt fair and filling.",
    "All in all, The app order matched exactly and they kept things moving.",
    "Good vibes: Loved how drive thru was easy today and the food was hot when i got it.",
    "For real, no complaints and the food was hot when i got it.",
    "Quick shoutout: chicken was super good and the food was hot when i got it.",
    "Just saying, Good to see the drive thru staff were upbeat.",
    "All in all, the store had a welcoming vibe and the food was hot when i got it.",
    "Quick shoutout: The combo was a good value and they kept things moving.",
    "Just saying, the counter staff smiled and kept it friendly.",
    "On this visit, I noticed counter staff were helpful and the pace stayed steady.",
    "Just saying, the sandwich held together and wasnt messy.",
    "For real, Pickup order was correct and the staff kept a warm vibe.",
    "On this visit, Food tasted great today and the crew was welcoming.",
    "Overall, really good food and it felt like a smooth visit.",
    "This time, the lobby was full but the tables were still clean.",
    "Quick shoutout: I appreciated the quick turnaround and they kept things moving.",
    "Just saying, change was counted correctly and it felt like a smooth visit.",
    "Honestly, Glad to see the meal was packaged neatly and everything came out right.",
    "Overall, Thanks yall for the quick bagging.",
    "Overall, the food smelled great in the car on the way home.",
    "This time, lobby smelled clean and the tables were wiped down.",
    "Quick shoutout: The experience was better than expected and the team stayed organized.",
    "Yall, made it easy and fast.",
    "All in all, order was packed correctly and the food was hot when i got it.",
    "Just saying, that was a W for sure.",
    "On this visit, the window worker was upbeat and friendly.",
    "Just saying, restaurant was clean and tidy.",
    "This time, the pickup shelf area was neat and uncluttered.",
    "Honestly, no complaints yall did great.",
    "Overall, Great food and friendly employees.",
    "For real, I noticed the sandwich was warm throughout.",
    "On this visit, Chicken sandwich was great and the pace stayed steady.",
    "Good vibes: they split the order into two bags for easier carry.",
    "Honestly, Pickup experience was great and the team stayed organized.",
    "Honestly, vibes were good and the food was hot.",
    "Good vibes: Pleasant staff and the staff kept it positive.",
    "For real, the chairs were clean and not sticky.",
    "Just saying, happy with how food was hot n tasty.",
    "For real, they were on it and it was fast.",
    "Overall, I noticed the chicken was not dry and the food was hot when i got it.",
    "On this visit, They followed my no pickles request and it was a pleasant visit.",
    "Just saying, the food was fire af.",
    "Good vibes: the line looked rough but it moved smooth.",
    "Just saying, Good portion sizes for the price and they kept things moving.",
    "For real, mobile pickup spot was clearly marked out front.",
    "Overall, The storefront windows were clean and it made the stop easy.",
    "This time, the food prep area looked clean and it felt like a smooth visit.",
    "For real, the lemonade was cold and refreshing.",
    "All in all, counter line was short and they kept things moving.",
    "This time, I noticed drive thru staff were nice and the pace stayed steady.",
    "Good vibes: got my food quick and they kept things moving.",
    "For real, solid stop and the food was hot.",
    "All in all, The utensils were included and everything came out right.",
    "Today, the crew was clutch during the rush.",
    "This time, Sandwich was tasty and it was a pleasant visit.",
    "For real, Sides were good and the pace stayed steady.",
    "On this visit, Everyone was nice and it felt easy from start to finish.",
    "Overall, the sauce options were tasty and the food was hot when i got it.",
    "All in all, Food was tasy and it felt easy from start to finish.",
    "For real, food was worth the price and it felt like a smooth visit.",
    "All in all, Glad to see dine in was nice and the food was hot when i got it.",
    "This time, Would come again and the team stayed organized.",
    "Just saying, the menu board was bright and readable.",
    "Today, Nice portion sizes and it made the stop easy.",
    "Today, Good customer service and it felt easy from start to finish.",
    "Quick shoutout: My payment was quick and easy.",
    "Just saying, drive thru was quick no cap.",
    "This time, the team was chill and quick.",
    "Good vibes: Alexander made the visit feel smooth and it made the stop easy.",
    "Overall, biscuits were so good and the team kept it pleasant.",
    "This time, nice ppl working here and the food was hot when i got it.",
    "Quick shoutout: The staff remembered my order and they kept things moving.",
    "Yall, made it easy for real.",
    "Quick shoutout: The store felt safe and well kept.",
    "Good vibes: The fryer oil tasted fresh, not old and it was a pleasant visit.",
    "Good vibes: super clutch with the quick pickup.",
    "Just saying, good looks on the quick order.",
    "Good vibes: The crew looked well trained and the staff stayed courteous.",
    "Quick shoutout: the food was bussin and quick.",
    "Quick shoutout: Appreciate how fast the service was and it felt like a smooth visit.",
    "Good vibes: Staff handled the lunch rush smoothly and the crew kept it upbeat.",
    "Honestly, Helpful staff and the team stayed organized.",
    "Today, the front door and windows looked clean.",
    "Honestly, Biscuits were flaky and the team stayed organized.",
    "Overall, the spicy chicken had a solid kick and good flavor.",
    "This time, The meal hit the spot and it felt easy from start to finish.",
    "All in all, the lobby was busy but it felt organized.",
    "Good vibes: The staff repeated my order to confirm and it made the stop easy.",
    "Just saying, Everything was exactly as requested and it made the stop easy.",
    "All in all, Drive thru line moved fast and the team stayed organized.",
    "On this visit, Orders were called out clearly and it felt easy from start to finish.",
    "Good vibes: Staff were friendly today and the pace stayed steady.",
    "Overall, The staff used polite language and they kept things moving.",
    "Overall, order came fast and the team stayed organized.",
    "Today, Food tasted consistent with past visits and it made the stop easy.",
    "This time, Coleslaw was good and it was a pleasant visit.",
    "Overall, Drive thru was easy and it was a pleasant visit.",
    "For real, the pickup area wasnt crowded and was easy to use.",
    "Overall, it was loud but they stayed polite and helpful.",
    "Quick shoutout: really liked the food and everything came out right.",
    "Honestly, The lobby music was pleasant and they kept things moving.",
    "Overall, service was awsome and it made the stop easy.",
    "For real, crispy and hot.",
    "Good vibes: drive thru was full but they were still quick.",
    "Today, The dine in area was comfortable and it was a pleasant visit.",
    "This time, Good value and it was a pleasant visit.",
    "Honestly, The team greeted me with a smile and they kept things moving.",
    "Honestly, the pickup shelf had my name spelled right.",
    "Overall, nice dinner and it felt like a smooth visit.",
    "Overall, Restrooms were stocked and clean.",
    "Honestly, The team handled a special request perfectly.",
    "Honestly, My order was double checked and correct.",
    "Just saying, the food was bussin and hot.",
    "This time, Tables were arranged nicely and the pace stayed steady.",
    "Good vibes: packed drive thru but the pace was steady.",
    "For real, Would come back and the pace stayed steady.",
    "For real, quick visit and the food was hot when i got it.",
    "Yall, handled the rush like pros.",
    "All in all, the dining room felt cozy and clean.",
    "All in all, the meal tasted fresh and made to order.",
    "Just saying, that was clutch and easy.",
    "All in all, the order number was called loud and clear.",
    "Good vibes: order was right and it made the stop easy.",
    "Today, fast service and good vibes.",
    "This time, the speaker box was clear and not crackly.",
    "Good vibes: they remembered my no pickle request.",
    "Quick shoutout: the food was on point today.",
    "All in all, Dine in was clean and comfy.",
    "Good vibes: the order number was called promptly.",
    "Today, good stop and it was a pleasant visit.",
    "Honestly, good vibes and a quick pickup.",
    "For real, The mashed potatoes were smooth and it made the stop easy.",
    "For real, the staff asked if i needed anything else before i left.",
    "All in all, Alexandar was real nice and polite.",
    "All in all, Happy to see the chicken was cooked evenly.",
    "Overall, michael jumped in and helped the crew.",
    "Quick shoutout: food was tasty and the food was hot when i got it.",
    "All in all, sandwich was fresh and they kept things moving.",
    "Honestly, the fries were hot af.",
    "On this visit, good looks on the fresh food.",
    "For real, Happy to see the sandwich was not squished.",
    "On this visit, place was packed but the staff kept it together.",
    "For real, my food was hot even after the short drive home.",
    "Just saying, the fries were hot and not soggy.",
    "For real, Fresh and hot.",
    "For real, i noticed drive thru order was right and the team stayed organized.",
    "This time, the bag had all the sauces and utensils i needed.",
    "Honestly, super smooth pickup and no wait.",
    "Overall, Nice staff and good food.",
    "On this visit, service was fast af.",
    "This time, really liked that drive thru was quick n easy.",
    "On this visit, the drive thru menu board was easy to read.",
    "Today, The meal came with everything I asked for.",
    "Honestly, Nice to see drive thru staff were helpful and the pace stayed steady.",
    "Honestly, that was a clean and quick visit.",
    "Overall, the bone in chicken was juicy and it felt like a smooth visit.",
    "This time, left with extra napkins and utensils without asking.",
    "Good vibes: Service was fast and everything came out right.",
    "All in all, Happy to see the order was packed carefully and it made the stop easy.",
    "On this visit, The food quality was consistent and everything came out right.",
    "All in all, Everything was hot and tasted fresh.",
    "Today, Thanks for the fast service yall.",
    "This time, the chicken tasted fresh and was still hot.",
    "Overall, the rush was real but the team handled it.",
    "Honestly, Trash bins were not overflowing and the staff kept it kind.",
    "Today, the order came out quick fr.",
    "This time, pickup was on time and it felt easy from start to finish.",
    "Honestly, The store looked well maintained and the team stayed organized.",
    "Good vibes: Pickup staff were friendly and it was a pleasant visit.",
    "Just saying, the crew was on it and friendly.",
    "Lowkey, loved the quick service.",
    "Quick shoutout: the drink station was clean and stocked.",
    "Honestly, The pickup shelf was organized and the team stayed polite.",
    "This time, chicken had a nice crunch and it felt like a smooth visit.",
    "All in all, the bag was sealed and everything was easy to carry.",
    "All in all, Nice people working here and it was a pleasant visit.",
    "All in all, The food tasted better than expected and the team stayed organized.",
    "Honestly, The store was spotless and it made the stop easy.",
    "Yall, were on it fr.",
    "All in all, Clean dining room and the pace stayed steady.",
    "Honestly, No wait today and they kept things moving.",
    "Good vibes: The mac and cheese was creamy.",
    "Good vibes: cashier was friendly and the food was hot when i got it.",
    "Just saying, real chill vibes in the lobby.",
    "Just saying, the lobby vibe was chill.",
    "For real, Michael checked the counter and kept it moving.",
    "Honestly, I appreciated the friendly greeting and it was a pleasant visit.",
    "This time, the meal was fire and hot.",
    "Quick shoutout: the chicken was cooked just right and the food was hot when i got it.",
    "Today, Mac n cheese was good and it made the stop easy.",
    "Overall, Manager Henry was awsome today and they kept things moving.",
    "Quick shoutout: i noticed drive thru was fast and the team stayed organized.",
    "On this visit, Good to see counter service was quick and the team stayed organized.",
    "For real, pickup was fast n easy and it felt like a smooth visit.",
    "Lowkey, the food was fire.",
    "Honestly, the order was bagged carefully and nothing was crushed.",
    "This time, The bag had all items listed and it made the stop easy.",
    "Just saying, the box was sealed well and the food was hot when i got it.",
    "Good vibes: the staff said bye and have a good one.",
    "Good vibes: the dining room chairs were clean and comfy.",
    "On this visit, Happy to see counter staff were polite.",
    "Just saying, the lobby was cool and comfortable on a hot day.",
    "Honestly, Food came out fast and the staff stayed warm.",
    "On this visit, that was a W visit.",
    "For real, Nice to see drive thru was quick and the crew stayed respectful.",
    "Good vibes: The beans were tender and the pace stayed steady.",
    "For real, The dining area stayed tidy and it was a pleasant visit.",
    "Overall, the sandwich sauce was balanced and the food was hot when i got it.",
    "Today, The spicy sauce had great flavor and it was a pleasant visit.",
    "Just saying, Napkins and sauces were included without asking.",
    "Just saying, Nice to see dine in was quick today and the pace stayed steady.",
    "This time, i noticed food was hot n fresh and everything came out right.",
    "Just saying, The ranch tasted fresh and they kept things moving.",
    "Honestly, The staff greeted me right away and it was a pleasant visit.",
    "For real, food was good n hot and the pace stayed steady.",
    "All in all, the sandwich had great flavor and texture.",
    "All in all, Food was fresh and everything came out right.",
    "Good vibes: the cashier was upbeat and polite.",
    "Quick shoutout: The counter staff made eye contact and the pace stayed steady.",
    "This time, the cajun seasoning was flavorful and the food was hot when i got it.",
    "Today, The chicken strips were tender and moist.",
    "On this visit, Short line and it was a pleasant visit.",
    "Honestly, They got my order right and the pace stayed steady.",
    "For real, the team worked smoothly together and it felt like a smooth visit.",
    "For real, Cajun fries were good and it made the stop easy.",
    "Quick shoutout: they called my number clearly and i heard it.",
    "This time, that was a W stop for sure.",
    "Honestly, The floor was spotless and the pace stayed steady.",
    "For real, wait looked long but it went faster than normal.",
    "On this visit, The biscuit was not dry and they kept things moving.",
    "For real, Order was done quick and everything came out right.",
    "Today, the lobby stayed chill even with people in it.",
    "Just saying, The trays were clean and it made the stop easy.",
    "Good vibes: drove through and the speaker was clear and easy to hear.",
    "On this visit, Nice to see drive thru was smooth today and everything came out right.",
    "Quick shoutout: took my food to go and the bag stayed sturdy.",
    "Quick shoutout: the app order was ready when i pulled up.",
    "For real, Great service in the drive thru and it made the stop easy.",
    "Overall, Freshly made and it felt easy from start to finish.",
    "Just saying, The manager checked on the dining room and the team stayed organized.",
    "Good vibes: The mac and cheese was rich.",
    "For real, Dine in staff were helpful and it was a pleasant visit.",
    "Overall, Everything was clean and organized.",
    "Quick shoutout: the line was long but yall flew through it.",
    "This time, they honored my no ice request without an issue.",
    "This time, was good today and the team stayed organized.",
    "Overall, They acknowledged me right away and the team kept it friendly.",
    "This time, they helped a customer ahead of me and stayed polite.",
    "Just saying, Counter line moved fast and the staff kept it chill.",
    "Honestly, parking was easy even during a busy hour.",
    "All in all, Henry checked in and kept the pace steady.",
    "Honestly, solid service and the food was hot.",
    "For real, No issues today and everything came out right.",
    "Overall, The sides were hot and fresh.",
    "Good vibes: The fries were crisp and well seasoned.",
    "This time, Happy to see counter service was great and it made the stop easy.",
    "Overall, they were quick even with a rush.",
    "This time, Cashier was nice and the team stayed organized.",
    "Just saying, the pickup shelf was easy to find and organized.",
    "On this visit, the window staff were friendly and kept it moving.",
    "All in all, The chicken crust did not fall off and everything came out right.",
    "Overall, Dine in tables were clean and the crew was kind.",
    "This time, service was smooth and the food was good.",
    "Good vibes: no stress and the order was correct.",
    "Honestly, I noticed the dine in seating was comfortable.",
    "Honestly, the store was busy but the vibe stayed chill.",
    "Good vibes: the pickup sign was easy to see and the food was hot when i got it.",
    "Quick shoutout: the lobby was quiet and relaxing.",
    "Today, The dipping sauce paired well and the pace stayed steady.",
    "Lowkey, loved how fast it was.",
    "Just saying, Loved how the drive thru lane was clean.",
    "This time, quick af and the order was right.",
    "All in all, they packed everything so it didnt spill.",
    "On this visit, the sandwich bun was fresh and soft.",
    "Today, food was gas and came out fast.",
    "No cap, the line moved fast.",
    "Today, Order taker was polite and they kept things moving.",
    "All in all, Everyone seemed focused and helpful.",
    "Quick shoutout: even with a big order ahead, they were quick.",
    "Just saying, Food was cooked well and it was a pleasant visit.",
    "On this visit, The tenders were a great size and it made the stop easy.",
    "Good vibes: Happy to see drive thru order was right.",
    "Quick shoutout: Michael was quick to fix a small mixup and everything came out right.",
    "On this visit, good looks yall.",
    "For real, shoutout to Michael for keeping the line moving.",
    "On this visit, Seasoning was on point and the team stayed welcoming.",
    "Just saying, the sides tasted fresh and came out hot.",
    "Honestly, the sandwich was fire no cap.",
    "This time, the receipt was in the bag and the order matched.",
    "This time, Food was hot and fresh.",
    "Overall, The drink lid was secure and it was a pleasant visit.",
    "Today, the staff kept the line moving efficiently.",
    "For real, stopped in with my order from the app and it was ready.",
    "Quick shoutout: solid visit and the food was fresh.",
    "Just saying, came in after work and the counter line was quick.",
    "On this visit, Spicy sandwich hit the spot and the staff were courteous.",
    "Honestly, the drive thru kept rolling.",
    "Good vibes: the cashier made sure my drinks were in the bag.",
    "Good vibes: Glad to see the order was ready right on time.",
    "Overall, The cashier explained the menu well and it made the stop easy.",
    "Today, The dining area smelled clean and fresh.",
    "This time, the staff stayed cool under pressure.",
    "On this visit, picked up food for the family and everything was packed right.",
    "Good vibes: Chicken was tender and the crew stayed upbeat.",
    "On this visit, The line for pickup was clear and everything came out right.",
    "Honestly, The drink station was clean and the team was polite.",
    "All in all, I appreciated how Micheal stayed visible and helpful.",
    "This time, michael made sure my bag was right and the pace stayed steady.",
    "On this visit, bathroom was stocked and looked clean.",
    "Today, the biscuits were warm when i opened the bag.",
    "Today, Fast and easy.",
    "Honestly, Michael made the visit feel easy and the team stayed organized.",
    "Overall, The beans and rice had great texture.",
    "Just saying, fast service and the food was gas.",
    "Good vibes: The chicken had great texture and everything came out right.",
    "Honestly, the sandwich was fresh af.",
    "Quick shoutout: the food was gas no lie.",
    "Overall, The crew worked well as a team and it made the stop easy.",
    "On this visit, the biscuit had a golden crust and it felt like a smooth visit.",
    "Quick shoutout: no problems at all and the food was hot when i got it.",
    "On this visit, parking lot was clean and easy to get in and out of.",
    "This time, The biscuits were buttery and warm.",
    "Honestly, Food was ready when I arrived and the staff stayed nice.",
    "Good vibes: picked up on my way home and the drive thru was smooth.",
    "For real, nice place and it felt like a smooth visit.",
    "Good vibes: this spot stays consistent fr.",
    "For real, the pickup was clutch and fast.",
    "Today, Quick service and good food.",
    "Just saying, The mild sandwich was flavorful and everything came out right.",
    "Honestly, friendly drive thru staff and it felt like a smooth visit.",
    "Quick shoutout: They were on top of it and it was a pleasant visit.",
    "Quick shoutout: quick stop and they kept things moving.",
    "Good vibes: No problems and they kept things moving.",
    "This time, food came out hot and fresh no cap.",
    "For real, The sweet tea was perfect and the pace stayed steady.",
    "Quick shoutout: friendly ppl and it felt like a smooth visit.",
    "On this visit, the chicken was cooked evenly and tasted great.",
    "Quick shoutout: Food was still hot when I got home and it was a pleasant visit.",
    "This time, happy with how counter service was quick today.",
    "All in all, Good to see the dine in service was quick and friendly.",
    "Honestly, food was delish and the pace stayed steady.",
    "All in all, The counter visit was fast and easy.",
    "This time, the breading stayed crispy and wasnt greasy.",
    "Quick shoutout: counter order was right and the food was hot when i got it.",
    "Overall, Michael was on top of the shift today and it made the stop easy.",
    "Good vibes: Thanks for the smooth drive thru.",
    "This time, the crew was chill and helpful.",
    "Quick shoutout: The store smelled like fresh food and it made the stop easy.",
    "This time, service was smooth fr and the food was hot.",
    "This time, Pickup was smooth and they kept things moving.",
    "No cap, yall were fast.",
    "Today, no wait at all and the food was hot when i got it.",
    "All in all, Fast service and it made the stop easy.",
    "Quick shoutout: the mac and cheese was creamy and rich.",
    "For real, Good meal and it made the stop easy.",
    "Honestly, grabbed a late dinner and the lobby was calm.",
    "Honestly, the biscuits were warm and buttery inside.",
    "On this visit, The bun held together well and the team stayed organized.",
    "On this visit, The sides were fresh and flavorful.",
    "All in all, drink lid was on tight and didnt leak in the car.",
    "Today, Everything tasted fresh and it felt easy from start to finish.",
    "On this visit, saw the manager checking on the lobby while i waited.",
    "Good vibes: staff was freindly and the crew kept a good vibe.",
    "Just saying, the drive thru was smooth fr.",
    "This time, The cashier had a positive attitude and the pace stayed steady.",
    "Just saying, Crew was helpful and the team kept it calm.",
    "This time, came in with a stroller and they made space for us.",
    "All in all, pickup was ready fast and the food was hot when i got it.",
    "Overall, The biscuits were really good and it was a pleasant visit.",
    "On this visit, stopped by on my lunch break and it was a fast visit.",
    "Good vibes: the fries were hot and crispy fr.",
    "Just saying, the parking lot lighting felt safe at night.",
    "Honestly, Chicken was crispy and it was a pleasant visit.",
    "Good vibes: everythin was good and everything came out right.",
    "Good vibes: stopped in after a long day and the staff still had good energy.",
    "Just saying, the sandwich bun was soft and held up well.",
    "Today, Service felt organized and efficient.",
    "No cap, the food hit the spot.",
    "No cap, the service was quick.",
    "On this visit, The breading stayed crunchy and everything came out right.",
    "On this visit, picked up for coworkers and the order was right.",
    "Today, the store was jumping but they kept it clean.",
    "Just saying, micheal checked on our order and smiled.",
    "Today, The drink was cold and refreshing.",
    "For real, the pickup order was labeled right with my name.",
    "Overall, the team kept the condiment area stocked.",
    "All in all, Everything was fine today and they kept things moving.",
    "Honestly, The order screen was accurate and the team stayed organized.",
    "Today, that was a solid W.",
    "For real, Counter staff were nice and the pace stayed steady.",
    "Today, Tasted great and it felt easy from start to finish.",
    "For real, The team handled my order quickly and the pace stayed steady.",
    "For real, Kind staff and they kept things moving.",
    "For real, this stop was a W.",
    "Quick shoutout: No delays and the staff kept it pleasant.",
    "All in all, The counter staff were attentive and they kept things moving.",
    "All in all, No missing items in the bag and the team stayed organized.",
    "Honestly, kids meal was packed right and the toy was inside.",
    "Overall, Thanks yall for keeping it quick.",
    "This time, the staff kept the counter clean and it felt like a smooth visit.",
    "On this visit, Alexander kept the rush calm and the line moving for sure.",
    "Quick shoutout: Service was quick and polite.",
    "Overall, The food hit the spot and they kept things moving.",
    "This time, traffic was busy but the drive thru was smooth.",
    "Overall, very freindly staff and everything came out right.",
    "Quick shoutout: the meal was legit af.",
    "Just saying, My receipt was accurate and the pace stayed steady.",
    "Quick shoutout: the sandwich lettuce was fresh and it felt like a smooth visit.",
    "Good vibes: the line moved fast and thats a W.",
    "For real, Parking lot looked tidy and the team stayed organized.",
    "Overall, The line looked long but moved fast and everything came out right.",
    "On this visit, The batter had good flavor and the crew stayed professional.",
    "On this visit, Michael was friendly, not rushed and the team was friendly.",
    "Today, Food was cooked good and it felt easy from start to finish.",
    "Quick shoutout: Good to see counter staff were friendly and it was a pleasant visit.",
    "Yall, were fast today and it felt easy.",
    "For real, the condiment area was clean and easy to use.",
    "No cap, the order was right.",
    "Today, the staff held the door for me which was nice.",
    "Honestly, alexander was professional but warm and it felt like a smooth visit.",
    "Honestly, the staff worked well even with a full lobby.",
    "Just saying, the counter line looked long but went quick.",
    "Honestly, They made my order without any confusion and everything came out right.",
    "Today, Service was great and it was a pleasant visit.",
    "Today, The mild chicken still had flavor.",
    "Just saying, I had a pleasant visit and it felt easy from start to finish.",
    "On this visit, Drive-thru moved quickly and the pace stayed steady.",
    "This time, they separated hot food from cold drinks in the bag.",
    "Quick shoutout: real chill vibes in here.",
    "Just saying, the speaker volume was good and i could hear clearly.",
    "Today, Happy to see the chicken was perfectly seasoned.",
    "Overall, the sandwich was hot all the way through.",
    "Good vibes: the counter was busy but they kept it smooth.",
    "This time, the crew helped a new worker and kept it smooth.",
    "Quick shoutout: Great taste and everything came out right.",
    "Overall, sandwich was hot and fresh.",
    "Quick shoutout: Chicken was crispy and hot.",
    "For real, Good to see drive thru was fast today and the pace stayed steady.",
    "Honestly, The gravy was tasty and not too salty.",
    "Quick shoutout: The restroom had soap and towels.",
    "Quick shoutout: The soda tasted fresh and it was a pleasant visit.",
    "Overall, Glad to see food was hot and tasy.",
    "Honestly, henry was cool and helpful.",
    "Today, sat by the window and it was quiet and comfy.",
    "Yall, were clutch with the sauces.",
    "Just saying, late night and they still had good energy.",
    "All in all, The crust stayed crispy on the drive home.",
    "Quick shoutout: Happy to see the drive thru order was read back correctly.",
    "Quick shoutout: the food was gas and fresh.",
    "Yall, were friendly and on it.",
    "On this visit, The queue moved steadily and everything came out right.",
    "Quick shoutout: The breading was seasoned evenly and it made the stop easy.",
    "Yall, were clutch today.",
    "Today, The manager thanked me personally.",
    "Yall, kept it moving fr.",
    "Good vibes: the biscuit was fluffy and not dry.",
    "This time, the pickup shelf was easy and quick.",
    "Good vibes: The tenders were juicy and tender.",
    "This time, the fries stayed hot on the ride back.",
    "Just saying, Portions were generous and the team stayed organized.",
    "This time, the counter was busy but yall stayed chill.",
    "Quick shoutout: got in and out fast no complaints.",
    "Just saying, The crew thanked me at the window and the pace stayed steady.",
    "Today, I noticed the order was assembled carefully.",
    "Good vibes: they offered extra sauce and i appreciated it.",
    "This time, Good to see good customer service and it felt like a smooth visit.",
    "Good vibes: the store was easy to spot from the road.",
    "This time, Really tasty and it was a pleasant visit.",
    "Quick shoutout: They got my order correct and everything came out right.",
    "All in all, Henry was out front and helping out.",
    "All in all, the chicken was crispy and hot.",
    "Overall, Bun was soft and they kept things moving.",
    "All in all, long line but the staff kept it moving steady.",
    "Honestly, I noticed the fries were not oily and the staff kept it respectful.",
    "This time, got extra napkins without asking which was nice.",
    "Good vibes: Pickup order ready on time and the pace stayed steady.",
    "Good vibes: solid service and good vibes.",
    "Honestly, Nice to see the fries were seasoned just right.",
    "For real, that meal hit and i was out.",
    "Honestly, Appreciate to Henry, everything felt organized and it made the stop easy.",
    "Today, Tomatoes looked fresh and bright.",
    "Honestly, the lobby was cool and comfortable after being outside.",
    "Just saying, the drive thru lane was clean and moved steady.",
    "This time, Food was flavorful and the pace stayed steady.",
    "Overall, everything was straight and easy.",
    "For real, The counter area was organized and it felt easy from start to finish.",
    "Quick shoutout: michael was super chill today and it made the stop easy.",
    "Quick shoutout: that was a smooth pickup for sure.",
    "Today, that spicy sandwich slapped.",
    "All in all, order came out clean and fast.",
    "On this visit, Staff were patient and everything came out right.",
    "All in all, Quick stop and go.",
    "Quick shoutout: Drive thru had no wait and it made the stop easy.",
    "Today, alexander checked in and was easy going.",
    "This time, it was raining and they still kept the pace up.",
    "Overall, i was in and out quickly.",
    "Honestly, good experience and it felt like a smooth visit.",
    "For real, Glad to see the fries were hot when served.",
    "Honestly, the crew was upbeat today and it felt like a smooth visit.",
    "On this visit, Chicken was flavorful and they kept things moving.",
    "Honestly, The meal felt freshly made and the crew stayed patient.",
    "Just saying, The pickup process was smooth and quick.",
    "Quick shoutout: Tables were wiped down quickly and it felt easy from start to finish.",
    "Yall, had good vibes today.",
    "Just saying, good energy from the staff.",
    "Honestly, fries were hot and the pace stayed steady.",
    "Lowkey, the best visit ive had here.",
    "Good vibes: that hit fr.",
    "Good vibes: the order was right and thats a W.",
    "Overall, the staff was real polite and helpful.",
    "On this visit, meal was hot and it felt easy from start to finish.",
    "Just saying, Micheal was very kind and helpfull.",
    "Today, Micheal was super nice about my request and the pace stayed steady.",
    "Overall, My order was ready in minutes and the team kept it easy.",
    "Overall, the chicken was bussin.",
    "Good vibes: the pickup parking spot was close to the door.",
    "Honestly, they wiped my table before i sat down.",
    "Overall, drive thru order was accurate and the food was hot when i got it.",
    "Today, pickup was smooth and everything came out right.",
    "For real, Food was delish today and the team stayed organized.",
    "Just saying, crowded night but my food still came out hot.",
    "This time, the drive thru was moving fr.",
    "Overall, the sauce tasted fresh and paired well.",
    "On this visit, Easy visit and everything came out right.",
    "On this visit, it was busy and they still checked on us.",
    "Today, the meal was hot and tasted fresh.",
    "This time, quick service and it felt like a smooth visit.",
    "Today, grabbed food before a movie and it was right on time.",
    "Today, quick stop and it hit the spot.",
    "Today, Extra napkins were appreciated and it felt easy from start to finish.",
    "Just saying, it was hectic but they stayed calm and professional.",
    "Good vibes: the kitchen was slammed but the order was right.",
    "This time, the tenders were juicy and not dry.",
    "Honestly, The sandwich was assembled neatly and everything came out right.",
    "On this visit, The food tasted like it was made to order and it was a pleasant visit.",
    "For real, Mac and cheese was good.",
    "Overall, came in during the rain and they were still fast.",
    "Overall, the rice and beans were well cooked.",
    "Honestly, they repeated my order and got it perfect.",
    "Quick shoutout: staff seemed swamped but still smiled.",
    "Just saying, The experience was smooth from start to finish.",
    "Good vibes: I noticed good customer service today and they kept things moving.",
    "Overall, Thanks for that the drive thru staff sounded cheerful.",
    "On this visit, Henry helped bag orders for a bit and it was a pleasant visit.",
    "This time, they got my extra sauce request right.",
    "Lowkey, a great visit.",
    "This time, The biscuit was fluffy inside and the pace stayed steady.",
    "This time, Staff kept things moving and the staff kept a friendly tone.",
    "Honestly, Nice stop and everything came out right.",
    "Quick shoutout: the fries were crisp even after the ride.",
    "Good vibes: Appreciated yall keeping it quick.",
    "This time, Pick up was easy and quick.",
    "Just saying, line was long but it moved quicker than i expected.",
    "On this visit, The bag was packed securely and it felt easy from start to finish.",
    "Overall, service was on point fr.",
    "Good vibes: the staff was cool af.",
    "Quick shoutout: Happy to see drive thru was quick and easy.",
    "On this visit, Appreciate that dine in was chill.",
    "Today, Really appreciated that drive thru was moving quick.",
    "Just saying, Solid meal and it was a pleasant visit.",
    "Good vibes: they gave me extra sauce and it made the meal better.",
    "Honestly, bun was fresh and it felt like a smooth visit.",
    "All in all, good vibes at the counter today.",
    "Honestly, that meal was gas and still hot.",
    "Today, i noticed drive thru was smooth and it made the stop easy.",
    "Quick shoutout: staff were cool and it felt easy from start to finish.",
    "Good vibes: the sandwich stayed crispy even after the drive.",
    "All in all, the pickup was smooth fr.",
    "Yall, were cool and helpful fr.",
    "All in all, Happy with how drive thru was fast n easy.",
    "Just saying, The coleslaw was crisp and it felt easy from start to finish.",
    "This time, food was greatt and it felt easy from start to finish.",
    "Honestly, manager michael made the visit easy and quick.",
    "Today, The food was worth the wait and the team stayed organized.",
    "This time, the food stayed warm even after a few errands.",
    "For real, the hand sink was clean and it felt like a smooth visit.",
    "On this visit, My order smelled amazing and it was a pleasant visit.",
    "Today, Food was packed neat and it felt easy from start to finish.",
    "On this visit, henry was attentive and helped the crew.",
    "Honestly, Really liked the crispy chicken and everything came out right.",
    "Overall, that biscuit slapped.",
    "Today, The coleslaw was creamy and fresh.",
    "Good vibes: Glad to see the drive thru speaker was clear.",
    "Today, the pickup label was correct and the food was hot when i got it.",
    "Good vibes: The staff moved with urgency and the team stayed organized.",
    "Today, the meal was legit and hot.",
    "This time, Counter was easy today and it made the stop easy.",
    "Honestly, they were short staffed but service was still solid.",
    "All in all, Michael and the crew worked great together.",
    "This time, The order was ready ahead of time and the pace stayed steady.",
    "All in all, Fries were hot and it made the stop easy.",
    "Overall, Appreciated the quick turnaround.",
    "Just saying, that hit the spot and i appreciate it.",
    "This time, Staff were welcoming and the pace stayed steady.",
    "Just saying, happy with how counter staff were friendly.",
    "All in all, the drive thru sign was easy to see.",
    "Overall, the cashier was friendly and made it easy.",
    "All in all, Service quality was good and the team stayed organized.",
    "For real, the sandwich portion was generous and the food was hot when i got it.",
    "Just saying, the fries were seasoned just right and stayed crisp.",
    "On this visit, the breading stayed on the chicken and the food was hot when i got it.",
    "Quick shoutout: that sandwich slapped and was fresh.",
    "Today, The kitchen looked organized and it was a pleasant visit.",
    "For real, i noticed the drive thru line moved steadily.",
    "Lowkey, a fast stop.",
    "All in all, the drive thru moved quick fr.",
    "On this visit, Thanks for yall being so quick.",
    "Honestly, The drive thru was efficient and organized.",
    "All in all, Food was warm and the pace stayed steady.",
    "All in all, The staff answered my question patiently.",
    "Today, the chicken was juicy with good seasoning.",
    "Today, the staff was cool and helpful.",
    "On this visit, good looks on the extra sauce.",
    "No cap, this was a smooth visit.",
    "Good vibes: food was fresh and the wait was short.",
    "Quick shoutout: Good visit and the crew kept it positive.",
    "On this visit, the order was right and that was clutch.",
    "Quick shoutout: The store was easy to get in and out of.",
    "All in all, the counter line moved faster than i expected.",
    "Good vibes: counter was crowded but service was smooth.",
    "This time, the gravy was smooth and had great flavor.",
    "Honestly, i had a coupon and they handled it with no hassle.",
    "Overall, ice was plentiful and clean.",
    "Good vibes: the rice and beans were cooked just right.",
    "All in all, food came out quick and it made the stop easy.",
    "Yall, made my day with that fast service.",
    "For real, the manager checked the floor while i waited.",
    "For real, The service felt professional and the pace stayed steady.",
    "This time, The lemonade tasted fresh and the team stayed kind.",
    "Yall, kept it moving and i appreciate it.",
    "Just saying, The food temperature was perfect and the staff stayed professional.",
    "Just saying, Alexander kept the rush calm and the line moving this time.",
    "Overall, The staff helped a customer ahead of me kindly.",
    "All in all, counter area looked tidy and well kept.",
    "Today, Happy to see food was hot and the crew kept it welcoming.",
    "All in all, Pickup was easy and the pace stayed steady.",
    "Good vibes: parking lot was well lit when i left."
  ]
};


