module.exports = {
  compliments: [
    "loved the spicy chicken sandwich and it felt easy overall.",
    "no cap that sandwich was fresh",
    "henry greeted me and made it simple",
    "Henry stayed calm and kept the rush smooth",
    "happy with how dine in was quick and it was a solid visit.",
    "drive thru moved fast even with a long line",
    "rush was heavy but they didnt miss a thing",
    "The nuggets were crisp and the pace stayed steady",
    "They brought my order to the table and service stayed smooth",
    "I noticed counter service was smooth.",
    "Chicken was hot and fresh",
    "the drive thru was clutch today",
    "thanks again yall that was fast",
    "the meal was hot and came out right",
    "the counter staff were upbeat and helpful.",
    "The batter was crispy without being greasy",
    "good spice level and the food was hot when i got it",
    "lowkey a smooth drive thru",
    "the sweet tea was just right",
    "The gravy was smooth and warm",
    "The staff stayed calm during a rush and it made things easy",
    "Food was packed well and everything was right",
    "they separated my kids meal from the spicy food",
    "they kept the line moving even with a big order ahead",
    "The spicy sandwich had a great kick.",
    "The rice was not dry and the wait stayed short",
    "Alexandar checked the lobby and said hi",
    "Pickup was ready when i got there and it made it simple",
    "Order was right and it felt smooth the whole time",
    "the staff asked if i needed anything else.",
    "Happy with how the drive thru window service was quick",
    "Drive thru staff were friendly and everything was right.",
    "the food was fire and fresh",
    "real quick stop and no stress",
    "Solid visit and it made the stop smooth.",
    "grabbed a quick bite before practice and it was on time.",
    "the drink tasted fresh and not flat",
    "brought the kids and the staff were patient and kind",
    "Dine in service was fast and the pace was consistent",
    "the coleslaw was crisp and fresh",
    "alexander checked the lobby and kept it tidy",
    "the dining room felt calm even with a few people",
    "The food smelled fresh and appetizing",
    "Service was fast even during busy time and it made things smooth",
    "yall kept it moving even with the rush",
    "ordered for a group and they kept it organized",
    "vibes were calm and the order was right",
    "the staff smiled and said have a good day",
    "the crew was on point fr",
    "red beans and rice were good.",
    "Food quality was good and it made things easy",
    "they kept the music low and it felt relaxed",
    "busy hour but they still got my order out fast",
    "they honored my extra sauce request and it was a smooth stop",
    "i noticed the meal was satisfying and hearty.",
    "The sandwich wrapper was clean and neat.",
    "the floor was dry and not slippery",
    "good energy from the crew today",
    "the cup was filled properly and it was a smooth stop.",
    "i noticed dine in was clean and it made the stop smooth.",
    "drive thru was backed up but the wait wasnt bad",
    "the cashier thanked me for coming in.",
    "nice to see the drive thru staff were friendly.",
    "Got my food quick in the drive thru",
    "trash bins were not overflowing in the dining room.",
    "The dining room was comfortable and the flow stayed steady",
    "the lobby was cool and comfortable",
    "Portions felt fair and filling",
    "The app order matched exactly and the line kept rolling",
    "Loved how drive thru was easy today and the food was hot when i got it",
    "no complaints and the food was hot when i got it",
    "chicken was super good and the food was hot when i got it.",
    "Glad to see the drive thru staff were upbeat.",
    "the store had a welcoming vibe and the food was hot when i got it",
    "The combo was a good value and the pace stayed on track",
    "the counter staff smiled and kept it friendly.",
    "I noticed counter staff were helpful and the pace felt steady.",
    "the sandwich held together and wasnt messy.",
    "really good food and it was a smooth stop",
    "the lobby was full but the tables were still clean",
    "I appreciated the quick turnaround and the crew kept the pace up",
    "change was counted correctly and it felt smooth overall",
    "Nice to see the meal was packaged neatly and everything was spot on",
    "thanks yall for the quick bagging",
    "the food smelled great in the car on the way home",
    "lobby smelled clean and the tables were wiped down",
    "yall made it easy and fast",
    "order was packed correctly and the food was hot when i got it.",
    "that was a W for sure",
    "the window worker was upbeat and friendly.",
    "restaurant was clean and tidy",
    "the pickup shelf area was neat and uncluttered",
    "no complaints yall did great",
    "Great food and friendly employees",
    "I noticed the sandwich was warm throughout",
    "Chicken sandwich was great and the pace stayed smooth",
    "they split the order into two bags for easier carry",
    "vibes were good and the food was hot",
    "the chairs were clean and not sticky",
    "happy with how food was hot n tasty.",
    "they were on it and it was fast",
    "I noticed the chicken was not dry and the food was hot when i got it",
    "They followed my no pickles request and it was a chill visit.",
    "the food was fire af",
    "the line looked rough but it moved smooth",
    "Good portion sizes for the price and the line moved along.",
    "mobile pickup spot was clearly marked out front",
    "The storefront windows were clean and it made it simple",
    "the food prep area looked clean and it was a smooth stop",
    "the lemonade was cold and refreshing",
    "counter line was short and the pace stayed smooth",
    "I noticed drive thru staff were nice and the pace felt steady.",
    "got my food quick and things stayed on track.",
    "solid stop and the food was hot",
    "The utensils were included and everything was just right",
    "the crew was clutch during the rush",
    "Sandwich was tasty and it was a nice visit.",
    "Sides were good and the pace felt smooth",
    "Everyone was nice and it felt smooth the whole time",
    "the sauce options were tasty and the food was hot when i got it.",
    "Food was tasy and it felt easy the whole way",
    "food was worth the price and it felt smooth overall.",
    "nice to see dine in was nice and the food was hot when i got it",
    "the menu board was bright and readable",
    "Nice portion sizes and it made the stop smooth",
    "Good customer service and it felt easy the whole way",
    "My payment was quick and easy",
    "drive thru was quick no cap",
    "the team was chill and quick",
    "Alexander made the visit feel smooth and it made the stop smooth",
    "nice ppl working here and the food was hot when i got it.",
    "The staff remembered my order and the line kept moving.",
    "yall made it easy for real",
    "The store felt safe and well kept",
    "The fryer oil tasted fresh, not old and it was a solid visit.",
    "super clutch with the quick pickup",
    "good looks on the quick order",
    "the food was bussin and quick",
    "appreciated how fast the service was and it was a smooth stop",
    "the front door and windows looked clean",
    "the spicy chicken had a solid kick and good flavor",
    "The meal hit the spot and it felt easy throughout.",
    "the lobby was busy but it felt organized",
    "The staff repeated my order to confirm and it made things smooth",
    "Everything was exactly as requested and it made the stop smooth.",
    "Orders were called out clearly and it felt easy the whole way",
    "Staff were friendly today and the pace felt steady.",
    "The staff used polite language and the pace held steady",
    "Food tasted consistent with past visits and it made things smooth",
    "Coleslaw was good and it was a solid visit.",
    "Drive thru was easy and it was a good stop",
    "the pickup area wasnt crowded and was easy to use",
    "it was loud but they stayed polite and helpful",
    "really liked the food and everything was accurate",
    "The lobby music was pleasant and the flow kept moving",
    "service was awsome and it made things easy.",
    "crispy and hot",
    "drive thru was full but they were still quick",
    "The dine in area was comfortable and it was a good experience",
    "Good value and it was a solid visit",
    "The team greeted me with a smile and the visit stayed smooth.",
    "the pickup shelf had my name spelled right",
    "nice dinner and it was easy and quick.",
    "Restrooms were stocked and clean",
    "The team handled a special request perfectly",
    "My order was double checked and correct",
    "the food was bussin and hot",
    "Tables were arranged nicely and the pace felt smooth",
    "packed drive thru but the pace was steady",
    "Would come back and the pace was steady.",
    "quick visit and the food was hot when i got it",
    "yall handled the rush like pros",
    "the dining room felt cozy and clean",
    "the meal tasted fresh and made to order",
    "that was clutch and easy",
    "the order number was called loud and clear",
    "order was right and it made the visit easy",
    "fast service and good vibes",
    "the speaker box was clear and not crackly",
    "they remembered my no pickle request",
    "the food was on point today",
    "Dine in was clean and comfy.",
    "the order number was called promptly.",
    "good stop and it was a good experience.",
    "good vibes and a quick pickup",
    "The mashed potatoes were smooth and it made things easy.",
    "the staff asked if i needed anything else before i left.",
    "Alexandar was real nice and polite",
    "Nice to see the chicken was cooked evenly",
    "michael jumped in and helped the crew.",
    "food was tasty and the food was hot when i got it.",
    "sandwich was fresh and service stayed quick",
    "the fries were hot af",
    "good looks on the fresh food",
    "Glad to see the sandwich was not squished.",
    "place was packed but the staff kept it together",
    "my food was hot even after the short drive home",
    "the fries were hot and not soggy",
    "Fresh and hot",
    "the bag had all the sauces and utensils i needed",
    "super smooth pickup and no wait",
    "Nice staff and good food",
    "service was fast af",
    "really liked that drive thru was quick n easy.",
    "the drive thru menu board was easy to read",
    "The meal came with everything I asked for",
    "glad to see drive thru staff were helpful and the pace felt steady.",
    "that was a clean and quick visit",
    "the bone in chicken was juicy and it was a smooth stop",
    "left with extra napkins and utensils without asking",
    "Service was fast and everything was correct.",
    "Glad to see the order was packed carefully and it made the visit easy",
    "The food quality was consistent and everything was spot on",
    "Everything was hot and tasted fresh",
    "thanks for the fast service yall",
    "the chicken tasted fresh and was still hot",
    "the rush was real but the team handled it",
    "the order came out quick fr",
    "pickup was on time and it felt smooth the whole time.",
    "Pickup staff were friendly and it was a solid visit",
    "the crew was on it and friendly",
    "lowkey loved the quick service",
    "the drink station was clean and stocked",
    "chicken had a nice crunch and it was a smooth stop.",
    "the bag was sealed and everything was easy to carry.",
    "Nice people working here and it was a good stop.",
    "The store was spotless and it made the visit easy",
    "yall were on it fr",
    "Clean dining room and the pace was consistent.",
    "No wait today and the pace didnt slip",
    "The mac and cheese was creamy.",
    "cashier was friendly and the food was hot when i got it.",
    "real chill vibes in the lobby",
    "the lobby vibe was chill",
    "Michael checked the counter and kept it moving",
    "I appreciated the friendly greeting and it was a good stop",
    "the meal was fire and hot",
    "the chicken was cooked just right and the food was hot when i got it.",
    "Mac n cheese was good and it made things smooth.",
    "Manager Henry was awsome today and the line kept moving along",
    "pickup was fast n easy and it felt easy overall.",
    "lowkey the food was fire",
    "the order was bagged carefully and nothing was crushed.",
    "The bag had all items listed and it made things smooth",
    "the box was sealed well and the food was hot when i got it",
    "the staff said bye and have a good one",
    "the dining room chairs were clean and comfy",
    "Nice to see counter staff were polite.",
    "the lobby was cool and comfortable on a hot day.",
    "that was a W visit",
    "The beans were tender and the pace stayed smooth",
    "The dining area stayed tidy and it was a nice visit",
    "the sandwich sauce was balanced and the food was hot when i got it",
    "The spicy sauce had great flavor and it was a good experience",
    "Napkins and sauces were included without asking",
    "glad to see dine in was quick today and the pace stayed smooth",
    "i noticed food was hot n fresh and everything was right",
    "The ranch tasted fresh and the pace kept steady",
    "The staff greeted me right away and it was a good experience.",
    "food was good n hot and the pace was steady",
    "the sandwich had great flavor and texture",
    "Food was fresh and everything was right",
    "the cashier was upbeat and polite",
    "The counter staff made eye contact and the pace was consistent.",
    "the cajun seasoning was flavorful and the food was hot when i got it",
    "The chicken strips were tender and moist",
    "Short line and it was a nice visit.",
    "They got my order right and the pace felt smooth.",
    "the team worked smoothly together and it was a smooth stop",
    "Cajun fries were good and it made the stop smooth",
    "they called my number clearly and i heard it.",
    "that was a W stop for sure",
    "The floor was spotless and the pace felt smooth.",
    "wait looked long but it went faster than normal",
    "The biscuit was not dry and the line stayed moving",
    "Order was done quick and everything was correct.",
    "the lobby stayed chill even with people in it",
    "The trays were clean and it made it simple",
    "drove through and the speaker was clear and easy to hear.",
    "Good to see drive thru was smooth today and everything was just right.",
    "took my food to go and the bag stayed sturdy",
    "the app order was ready when i pulled up",
    "Great service in the drive thru and it made it simple.",
    "Freshly made and it felt smooth the whole time.",
    "The mac and cheese was rich",
    "Dine in staff were helpful and it was a good stop",
    "Everything was clean and organized",
    "the line was long but yall flew through it",
    "they honored my no ice request without an issue",
    "they helped a customer ahead of me and stayed polite",
    "parking was easy even during a busy hour",
    "Henry checked in and kept the pace steady",
    "solid service and the food was hot",
    "No issues today and everything was accurate",
    "The sides were hot and fresh",
    "The fries were crisp and well seasoned",
    "nice to see counter service was great and it made the visit easy",
    "they were quick even with a rush",
    "the pickup shelf was easy to find and organized",
    "the window staff were friendly and kept it moving",
    "The chicken crust did not fall off and everything was correct",
    "service was smooth and the food was good",
    "no stress and the order was correct",
    "I noticed the dine in seating was comfortable",
    "the store was busy but the vibe stayed chill",
    "the pickup sign was easy to see and the food was hot when i got it.",
    "the lobby was quiet and relaxing.",
    "The dipping sauce paired well and the pace felt smooth",
    "lowkey loved how fast it was",
    "Loved how the drive thru lane was clean",
    "quick af and the order was right",
    "they packed everything so it didnt spill",
    "the sandwich bun was fresh and soft",
    "food was gas and came out fast",
    "no cap the line moved fast",
    "Order taker was polite and service stayed on track",
    "Everyone seemed focused and helpful",
    "even with a big order ahead, they were quick",
    "Food was cooked well and it was a good experience.",
    "The tenders were a great size and it made the stop smooth.",
    "Glad to see drive thru order was right",
    "Michael was quick to fix a small mixup and everything was right.",
    "good looks yall",
    "shoutout to Michael for keeping the line moving",
    "the sides tasted fresh and came out hot",
    "the sandwich was fire no cap",
    "the receipt was in the bag and the order matched",
    "Food was hot and fresh.",
    "The drink lid was secure and it was a good experience",
    "the staff kept the line moving efficiently.",
    "stopped in with my order from the app and it was ready",
    "solid visit and the food was fresh",
    "came in after work and the counter line was quick",
    "the drive thru kept rolling",
    "the cashier made sure my drinks were in the bag",
    "Nice to see the order was ready right on time",
    "The cashier explained the menu well and it made the visit easy",
    "The dining area smelled clean and fresh.",
    "the staff stayed cool under pressure",
    "picked up food for the family and everything was packed right",
    "The line for pickup was clear and everything was correct",
    "I appreciated how Micheal stayed visible and helpful",
    "michael made sure my bag was right and the pace felt smooth.",
    "bathroom was stocked and looked clean",
    "the biscuits were warm when i opened the bag",
    "Fast and easy",
    "The beans and rice had great texture",
    "fast service and the food was gas",
    "The chicken had great texture and everything was accurate",
    "the sandwich was fresh af",
    "the food was gas no lie",
    "The crew worked well as a team and it made the visit easy",
    "the biscuit had a golden crust and it was easy and quick",
    "no problems at all and the food was hot when i got it.",
    "parking lot was clean and easy to get in and out of",
    "The biscuits were buttery and warm.",
    "picked up on my way home and the drive thru was smooth",
    "nice place and it was easy and quick",
    "this spot stays consistent fr",
    "the pickup was clutch and fast",
    "Quick service and good food.",
    "The mild sandwich was flavorful and everything was right",
    "friendly drive thru staff and it was easy and quick",
    "They were on top of it and it was a good experience",
    "quick stop and the line kept steady",
    "No problems and the pace stayed consistent.",
    "food came out hot and fresh no cap",
    "The sweet tea was perfect and the pace felt smooth",
    "friendly ppl and it was a smooth stop",
    "the chicken was cooked evenly and tasted great",
    "Food was still hot when I got home and it was a good stop",
    "happy with how counter service was quick today",
    "glad to see the dine in service was quick and friendly.",
    "food was delish and the pace was consistent.",
    "The counter visit was fast and easy.",
    "the breading stayed crispy and wasnt greasy",
    "counter order was right and the food was hot when i got it.",
    "Michael was on top of the shift today and it made it simple.",
    "appreciate the smooth drive thru",
    "the crew was chill and helpful",
    "The store smelled like fresh food and it made things easy",
    "service was smooth fr and the food was hot",
    "Pickup was smooth and the wait stayed light",
    "no cap yall were fast",
    "no wait at all and the food was hot when i got it",
    "Fast service and it made things easy",
    "the mac and cheese was creamy and rich",
    "Good meal and it made it simple",
    "grabbed a late dinner and the lobby was calm",
    "the biscuits were warm and buttery inside",
    "The sides were fresh and flavorful",
    "drink lid was on tight and didnt leak in the car",
    "Everything tasted fresh and it was easy all the way",
    "saw the manager checking on the lobby while i waited",
    "the drive thru was smooth fr",
    "The cashier had a positive attitude and the pace stayed smooth",
    "came in with a stroller and they made space for us",
    "pickup was ready fast and the food was hot when i got it",
    "The biscuits were really good and it was a good experience.",
    "stopped by on my lunch break and it was a fast visit",
    "the fries were hot and crispy fr",
    "the parking lot lighting felt safe at night",
    "Chicken was crispy and it was a chill visit",
    "everythin was good and everything was accurate.",
    "stopped in after a long day and the staff still had good energy",
    "the sandwich bun was soft and held up well",
    "Service felt organized and efficient",
    "no cap the food hit the spot",
    "no cap the service was quick",
    "The breading stayed crunchy and everything was just right",
    "picked up for coworkers and the order was right",
    "the store was jumping but they kept it clean",
    "micheal checked on our order and smiled",
    "The drink was cold and refreshing.",
    "the pickup order was labeled right with my name",
    "the team kept the condiment area stocked",
    "Everything was fine today and the line kept up",
    "that was a solid W",
    "Counter staff were nice and the pace was consistent",
    "Tasted great and it went smooth end to end.",
    "The team handled my order quickly and the pace stayed smooth",
    "Kind staff and the pace stayed strong",
    "this stop was a W",
    "The counter staff were attentive and the line kept a steady flow.",
    "kids meal was packed right and the toy was inside",
    "thanks yall for keeping it quick",
    "the staff kept the counter clean and it felt smooth overall",
    "Alexander kept the rush calm and the line moving for sure",
    "Service was quick and polite.",
    "The food hit the spot and the pace stayed even",
    "traffic was busy but the drive thru was smooth",
    "very freindly staff and everything was right",
    "the meal was legit af",
    "My receipt was accurate and the pace was consistent",
    "the sandwich lettuce was fresh and it was easy and simple",
    "the line moved fast and thats a W",
    "The line looked long but moved fast and everything was right",
    "Food was cooked good and it was easy all the way.",
    "Glad to see counter staff were friendly and it was a good experience.",
    "yall were fast today and it felt easy",
    "the condiment area was clean and easy to use",
    "no cap the order was right",
    "the staff held the door for me which was nice",
    "alexander was professional but warm and it was a smooth stop",
    "the staff worked well even with a full lobby",
    "the counter line looked long but went quick",
    "They made my order without any confusion and everything was right",
    "Service was great and it was a chill visit",
    "The mild chicken still had flavor.",
    "I had a pleasant visit and it went smooth end to end.",
    "Drive-thru moved quickly and the pace stayed smooth.",
    "they separated hot food from cold drinks in the bag",
    "real chill vibes in here",
    "the speaker volume was good and i could hear clearly",
    "Glad to see the chicken was perfectly seasoned",
    "the sandwich was hot all the way through",
    "the counter was busy but they kept it smooth",
    "the crew helped a new worker and kept it smooth.",
    "Great taste and everything was accurate",
    "sandwich was hot and fresh",
    "Chicken was crispy and hot.",
    "Glad to see drive thru was fast today and the pace felt steady.",
    "The gravy was tasty and not too salty",
    "The restroom had soap and towels.",
    "The soda tasted fresh and it was a solid visit",
    "nice to see food was hot and tasy.",
    "henry was cool and helpful",
    "sat by the window and it was quiet and comfy",
    "yall were clutch with the sauces",
    "late night and they still had good energy",
    "The crust stayed crispy on the drive home",
    "Good to see the drive thru order was read back correctly.",
    "the food was gas and fresh",
    "yall were friendly and on it",
    "The queue moved steadily and everything was just right.",
    "The breading was seasoned evenly and it made things easy",
    "yall were clutch today",
    "The manager thanked me personally",
    "yall kept it moving fr",
    "the biscuit was fluffy and not dry",
    "the pickup shelf was easy and quick",
    "The tenders were juicy and tender",
    "the fries stayed hot on the ride back",
    "the counter was busy but yall stayed chill",
    "got in and out fast no complaints",
    "The crew thanked me at the window and the pace stayed smooth",
    "I noticed the order was assembled carefully",
    "they offered extra sauce and i appreciated it.",
    "glad to see good customer service and it was a smooth stop",
    "the store was easy to spot from the road",
    "Really tasty and it was a good stop",
    "They got my order correct and everything was right",
    "Henry was out front and helping out",
    "the chicken was crispy and hot",
    "Bun was soft and service stayed on pace.",
    "long line but the staff kept it moving steady",
    "got extra napkins without asking which was nice",
    "Pickup order ready on time and the pace felt smooth",
    "solid service and good vibes",
    "glad to see the fries were seasoned just right.",
    "that meal hit and i was out",
    "Thanks to Henry, everything felt organized and it made the visit easy",
    "Tomatoes looked fresh and bright",
    "the lobby was cool and comfortable after being outside",
    "the drive thru lane was clean and moved steady",
    "Food was flavorful and the pace stayed smooth",
    "everything was straight and easy",
    "The counter area was organized and it was easy all the way",
    "michael was super chill today and it made things smooth",
    "that was a smooth pickup for sure",
    "that spicy sandwich slapped",
    "order came out clean and fast",
    "Staff were patient and everything was spot on",
    "Quick stop and go",
    "Drive thru had no wait and it made the stop smooth",
    "alexander checked in and was easy going.",
    "it was raining and they still kept the pace up",
    "i was in and out quickly",
    "good experience and it was a smooth stop",
    "Nice to see the fries were hot when served",
    "the crew was upbeat today and it felt easy overall",
    "Chicken was flavorful and the line kept a steady pace.",
    "The pickup process was smooth and quick",
    "Tables were wiped down quickly and it felt smooth the whole time",
    "yall had good vibes today",
    "good energy from the staff",
    "fries were hot and the pace felt steady",
    "lowkey the best visit ive had here",
    "that hit fr",
    "the order was right and thats a W",
    "the staff was real polite and helpful",
    "meal was hot and it felt easy throughout.",
    "Micheal was very kind and helpfull",
    "Micheal was super nice about my request and the pace was consistent",
    "the chicken was bussin",
    "the pickup parking spot was close to the door",
    "they wiped my table before i sat down",
    "drive thru order was accurate and the food was hot when i got it.",
    "pickup was smooth and everything was accurate",
    "crowded night but my food still came out hot",
    "the drive thru was moving fr",
    "the sauce tasted fresh and paired well",
    "Easy visit and everything was spot on.",
    "it was busy and they still checked on us",
    "the meal was hot and tasted fresh",
    "quick service and it felt easy overall",
    "grabbed food before a movie and it was right on time",
    "quick stop and it hit the spot",
    "Extra napkins were appreciated and it felt smooth the whole time",
    "it was hectic but they stayed friendly and calm",
    "the kitchen was slammed but the order was right",
    "the tenders were juicy and not dry",
    "The sandwich was assembled neatly and everything was spot on.",
    "The food tasted like it was made to order and it was a good experience.",
    "Mac and cheese was good",
    "came in during the rain and they were still fast",
    "the rice and beans were well cooked.",
    "they repeated my order and got it perfect",
    "staff seemed swamped but still smiled",
    "The experience was smooth from start to finish",
    "I noticed good customer service today and the flow stayed smooth",
    "appreciated that the drive thru staff sounded cheerful.",
    "Henry helped bag orders for a bit and it was a chill visit",
    "they got my extra sauce request right",
    "lowkey a great visit",
    "The biscuit was fluffy inside and the pace stayed smooth",
    "Nice stop and everything was right.",
    "the fries were crisp even after the ride",
    "appreciate yall keeping it quick",
    "Pick up was easy and quick",
    "line was long but it moved quicker than i expected",
    "The bag was packed securely and it felt easy throughout",
    "service was on point fr",
    "the staff was cool af",
    "nice to see drive thru was quick and easy.",
    "appreciated that dine in was chill.",
    "appreciated that drive thru was moving quick.",
    "Solid meal and it was a chill visit",
    "they gave me extra sauce and it made the meal better",
    "bun was fresh and it was easy and simple",
    "good vibes at the counter today",
    "that meal was gas and still hot",
    "i noticed drive thru was smooth and it made it simple",
    "staff were cool and it felt smooth the whole time.",
    "the sandwich stayed crispy even after the drive",
    "the pickup was smooth fr",
    "yall were cool and helpful fr",
    "Happy with how drive thru was fast n easy.",
    "The coleslaw was crisp and it felt smooth the whole time",
    "food was greatt and it went smooth end to end",
    "manager michael made the visit easy and quick",
    "the food stayed warm even after a few errands.",
    "the hand sink was clean and it was easy and quick",
    "My order smelled amazing and it was a good experience",
    "Food was packed neat and it went smooth end to end",
    "henry was attentive and helped the crew",
    "Really liked the crispy chicken and everything was right",
    "that biscuit slapped",
    "The coleslaw was creamy and fresh",
    "Nice to see the drive thru speaker was clear",
    "the pickup label was correct and the food was hot when i got it",
    "the meal was legit and hot",
    "Counter was easy today and it made it simple",
    "they were short staffed but service was still solid",
    "Michael and the crew worked great together",
    "The order was ready ahead of time and the pace stayed smooth",
    "Fries were hot and it made the visit easy.",
    "appreciate the quick turnaround",
    "that hit the spot and i appreciate it",
    "Staff were welcoming and the pace was steady",
    "happy with how counter staff were friendly.",
    "the drive thru sign was easy to see",
    "the cashier was friendly and made it easy",
    "the sandwich portion was generous and the food was hot when i got it",
    "the fries were seasoned just right and stayed crisp",
    "the breading stayed on the chicken and the food was hot when i got it",
    "that sandwich slapped and was fresh",
    "The kitchen looked organized and it was a chill visit",
    "i noticed the drive thru line moved steadily.",
    "lowkey a fast stop",
    "the drive thru moved quick fr",
    "appreciate yall being so quick",
    "The drive thru was efficient and organized",
    "Food was warm and the pace was consistent.",
    "The staff answered my question patiently.",
    "the chicken was juicy with good seasoning",
    "the staff was cool and helpful",
    "good looks on the extra sauce",
    "no cap this was a smooth visit",
    "food was fresh and the wait was short",
    "the order was right and that was clutch",
    "The store was easy to get in and out of",
    "the counter line moved faster than i expected",
    "counter was crowded but service was smooth",
    "the gravy was smooth and had great flavor",
    "i had a coupon and they handled it with no hassle",
    "ice was plentiful and clean",
    "the rice and beans were cooked just right",
    "food came out quick and it made things smooth",
    "yall made my day with that fast service",
    "the manager checked the floor while i waited",
    "The service felt professional and the pace felt steady",
    "yall kept it moving and i appreciate it",
    "Alexander kept the rush calm and the line moving this time",
    "The staff helped a customer ahead of me kindly",
    "counter area looked tidy and well kept",
    "Pickup was easy and the pace felt steady.",
    "parking lot was well lit when i left"
  ]
};



