module.exports = {
  compliments: [
    "good energy from the crew today",
    "Pick up was easy and quick and the staff kept things moving",
    "the food prep area looked clean and it felt like a smooth visit",
    "the tenders were juicy and not dry",
    "the staff stayed cool under pressure",
    "the counter line looked long but went quick",
    "The coleslaw was creamy and fresh and it felt easy from start to finish",
    "they honored my extra sauce request and it felt like a smooth visit",
    "happy with how counter staff were friendly and the staff kept things moving.",
    "the lobby was busy but it felt organized",
    "the fries were seasoned just right and stayed crisp",
    "I noticed the sandwich was warm throughout and the food was hot when i got it",
    "no stress and the order was correct",
    "order was packed correctly and the food was hot when i got it.",
    "Glad to see counter staff were friendly and it was a pleasant visit.",
    "I noticed counter service was smooth and it felt easy from start to finish.",
    "Glad to see the order was packed carefully and it made the stop easy",
    "the food was fire and fresh",
    "The order was ready ahead of time and the pace stayed steady",
    "kids meal was packed right and the toy was inside",
    "yall had good vibes today",
    "Micheal was attentve and respectful and it was a pleasant visit",
    "the team worked smoothly together and it felt like a smooth visit",
    "yall handled the rush like pros",
    "alexander thanked us for coming in and the food was hot when i got it",
    "yall were fast today and it felt easy",
    "The fries were crisp and well seasoned and it made the stop easy",
    "i was in and out quickly and the food was hot when i got it",
    "crispy and hot and the food was hot when i got it",
    "Portions were generous and the team stayed organized",
    "the sandwich had great flavor and texture",
    "The food was worth the wait and the team stayed organized.",
    "Chicken was crispy and it was a pleasant visit",
    "Alexander handled a busy moment well and the staff kept things moving",
    "No wait today and the staff kept things moving",
    "the gravy was smooth and had great flavor",
    "the cashier was upbeat and polite and it felt like a smooth visit",
    "the dining room felt calm even with a few people",
    "parking lot was well lit when i left",
    "the pickup was clutch and fast",
    "The gravy was tasty and not too salty and it was a pleasant visit",
    "parking lot was clean and easy to get in and out of",
    "that hit the spot and i appreciate it",
    "Nice portion sizes and it made the stop easy",
    "the fries were hot af",
    "the food was bussin and quick",
    "the pickup label was correct and the food was hot when i got it",
    "the drive thru sign was easy to see",
    "The store looked well maintained and the team stayed organized.",
    "quick stop and it hit the spot",
    "good looks yall",
    "My order smelled amazing and it was a pleasant visit",
    "The biscuit was not dry and the staff kept things moving",
    "bun was fresh and it felt like a smooth visit",
    "They got my order correct and everything came out right",
    "Pickup experience was great and the team stayed organized",
    "the drink tasted fresh and not flat",
    "the receipt was in the bag and the order matched",
    "Micheal was super nice about my request and the pace stayed steady",
    "appreciate the quick turnaround",
    "Alexander kept the rush calm and the line moving this time",
    "Helpful staff and the team stayed organized.",
    "The staff used polite language and the staff kept things moving",
    "the hand sink was clean and it felt like a smooth visit",
    "cashier was friendly and the food was hot when i got it.",
    "it was busy and they still checked on us",
    "vibes were good and the food was hot",
    "The meal came with everything I asked for and the service stayed friendly",
    "the cashier made sure my drinks were in the bag",
    "Food came out fast and the service stayed friendly.",
    "the app order was ready when i pulled up",
    "really liked the food and everything came out right",
    "the sandwich portion was generous and the food was hot when i got it",
    "the order came out quick fr",
    "the menu board was bright and readable",
    "Nice to see the fries were hot when served and it felt like a smooth visit",
    "Extra napkins were appreciated and it felt easy from start to finish",
    "traffic was busy but the drive thru was smooth",
    "The meal hit the spot and it felt easy from start to finish.",
    "lowkey loved the quick service",
    "I appreciated the friendly greeting and it was a pleasant visit",
    "Pickup was smooth and the staff kept things moving",
    "henry greeted me and made it simple and it felt like a smooth visit",
    "The counter staff made eye contact and the pace stayed steady.",
    "michael kept things smooth at the counter and it felt like a smooth visit.",
    "No delays and the service stayed friendly",
    "the order was right and that was clutch",
    "Portions felt fair and filling and the pace stayed steady",
    "order came out clean and fast",
    "the rush was real but the team handled it",
    "The team handled my order quickly and the pace stayed steady",
    "thanks for the fast service yall",
    "Chicken was tender and the service stayed friendly",
    "drive thru was full but they were still quick",
    "Glad to see drive thru was fast today and the pace stayed steady.",
    "The restroom had soap and towels and it was a pleasant visit.",
    "The beans were tender and the pace stayed steady",
    "Nice people working here and it was a pleasant visit.",
    "the counter was busy but yall stayed chill",
    "drink lid was on tight and didnt leak in the car",
    "the window worker was upbeat and friendly.",
    "The staff greeted me right away and it was a pleasant visit.",
    "Dine in service was fast and the pace stayed steady",
    "that was clutch and easy",
    "michael kept the dining room looking good and the food was hot when i got it.",
    "lowkey loved how fast it was",
    "Glad to see food was hot and the service stayed friendly.",
    "the lobby was quiet and relaxing and the food was hot when i got it.",
    "the chicken was crispy and hot",
    "Good value and it was a pleasant visit",
    "the chairs were clean and not sticky",
    "Solid visit and it made the stop easy.",
    "the drive thru moved quick fr",
    "The breading was seasoned evenly and it made the stop easy",
    "Manager Henry was awsome today and the staff kept things moving",
    "The staff remembered my order and the staff kept things moving.",
    "Michael was quick to fix a small mixup and everything came out right.",
    "Food was flavorful and the pace stayed steady",
    "biscuits were so good and the service stayed friendly.",
    "No problems and the staff kept things moving.",
    "late night and they still had good energy",
    "the pickup area wasnt crowded and was easy to use",
    "it was raining and they still kept the pace up",
    "Great value for a filling meal and the service stayed friendly.",
    "they helped a customer ahead of me and stayed polite",
    "Parking lot looked tidy and the team stayed organized",
    "Everything was clean and organized and it made the stop easy",
    "service was on point fr",
    "that was a W visit",
    "The floor was spotless and the pace stayed steady.",
    "lowkey a smooth drive thru",
    "Food tasted great today and the service stayed friendly",
    "The chicken crust did not fall off and everything came out right",
    "the counter staff were upbeat and helpful.",
    "glad to see counter service was quick and the team stayed organized",
    "The food smelled fresh and appetizing and it was a pleasant visit",
    "The store felt safe and well kept and it felt easy from start to finish",
    "The sides were fresh and flavorful and the staff kept things moving",
    "the cashier thanked me for coming in and the food was hot when i got it.",
    "it was hectic but they stayed friendly and calm",
    "Henry was polite, no attitude and it was a pleasant visit",
    "Would come back and the pace stayed steady.",
    "place was packed but the staff kept it together",
    "quick stop and the staff kept things moving",
    "the sandwich sauce was balanced and the food was hot when i got it",
    "The tenders were juicy and tender and the team stayed organized",
    "Michael stayed polite even when it got busy and the team stayed organized",
    "they honored my no ice request without an issue",
    "Food tasted consistent with past visits and it made the stop easy",
    "yall kept it moving fr",
    "The cashier had a positive attitude and the pace stayed steady",
    "Food was packed neat and it felt easy from start to finish",
    "drive thru was backed up but the wait wasnt bad",
    "I appreciated how Micheal stayed visible and helpful",
    "the counter line moved faster than i expected",
    "the spicy chicken had a solid kick and good flavor",
    "Michael made the visit feel easy and the team stayed organized",
    "sandwich was fresh and the staff kept things moving",
    "Service quality was good and the team stayed organized",
    "got in and out fast no complaints",
    "yall kept it moving and i appreciate it",
    "no complaints yall did great",
    "the cup was filled properly and it felt like a smooth visit.",
    "I had a pleasant visit and it felt easy from start to finish.",
    "the store had a welcoming vibe and the food was hot when i got it",
    "i had a coupon and they handled it with no hassle",
    "Pickup order was correct and the service stayed friendly",
    "The queue moved steadily and everything came out right.",
    "meal was hot and it felt easy from start to finish.",
    "They were on top of it and it was a pleasant visit",
    "the pickup order was labeled right with my name",
    "The drink station was clean and the service stayed friendly",
    "the speaker box was clear and not crackly",
    "Loved how drive thru was easy today and the food was hot when i got it",
    "Food was delish today and the team stayed organized",
    "Cajun fries were hot and the team stayed organized.",
    "stopped by on my lunch break and it was a fast visit",
    "Henry was polite and to the point and the team stayed organized",
    "no cap the food hit the spot",
    "packed drive thru but the pace was steady",
    "The dining area smelled clean and fresh and it made the stop easy.",
    "the crew was on it and friendly",
    "my food was hot even after the short drive home",
    "loved the spicy chicken sandwich and it felt like a smooth visit.",
    "the drink station was clean and stocked",
    "pickup was on time and it felt easy from start to finish.",
    "Restrooms were stocked and clean and everything came out right",
    "good experience and it felt like a smooth visit",
    "the sandwich was fresh af",
    "parking was easy even during a busy hour",
    "service was smooth fr and the food was hot",
    "the drive thru was moving fr",
    "hot food fast and the team stayed organized.",
    "super smooth pickup and no wait",
    "friendly drive thru staff and it felt like a smooth visit",
    "Henery was nice and very helpfull and it felt easy from start to finish",
    "Fresh and hot and everything came out right",
    "food was fresh and the wait was short",
    "The experience was better than expected and the team stayed organized",
    "glad to see good customer service and it felt like a smooth visit",
    "nice ppl working here and the food was hot when i got it.",
    "The lemonade tasted fresh and the service stayed friendly",
    "the chicken was juicy with good seasoning",
    "solid service and the food was hot",
    "Orders were called out clearly and it felt easy from start to finish",
    "I appreciated the quick turnaround and the staff kept things moving",
    "they kept the music low and it felt relaxed",
    "The staff moved with urgency and the team stayed organized",
    "The gravy was smooth and warm and everything came out right",
    "fries were hot and the pace stayed steady",
    "Easy visit and everything came out right.",
    "I noticed good customer service today and the staff kept things moving",
    "the rice and beans were well cooked and it felt like a smooth visit.",
    "food came out hot and fresh no cap",
    "the fries were crisp even after the ride",
    "the sandwich lettuce was fresh and it felt like a smooth visit",
    "Seasoning was on point and the service stayed friendly.",
    "Food quality was good and it made the stop easy",
    "the fries were hot and crispy fr",
    "The gravy had good flavor and the team stayed organized",
    "The beans and rice had great texture and everything came out right",
    "alexander checked in and was easy going and it felt like a smooth visit.",
    "The chicken had great texture and everything came out right",
    "that spicy sandwich slapped",
    "Loved how the drive thru lane was clean and the service stayed friendly",
    "they separated hot food from cold drinks in the bag",
    "the food was on point today",
    "The ranch tasted fresh and the staff kept things moving",
    "Biscuits were warm and the team stayed organized.",
    "The manager checked on the dining room and the team stayed organized",
    "Service was fast even during busy time and it made the stop easy",
    "the team kept the condiment area stocked",
    "The trays were clean and it made the stop easy",
    "Food was cooked well and it was a pleasant visit.",
    "The crew looked well trained and the service stayed friendly",
    "pickup was ready fast and the food was hot when i got it",
    "Everything was hot and tasted fresh and it made the stop easy",
    "Fast and easy and it made the stop easy",
    "Pleasant staff and the service stayed friendly.",
    "the manager checked the floor while i waited",
    "The mild sandwich was flavorful and everything came out right",
    "The biscuits were buttery and warm and the service stayed friendly.",
    "glad to see the meal was satisfying and the team stayed organized",
    "stopped in with my order from the app and it was ready",
    "My order was ready in minutes and the service stayed friendly",
    "The spicy sauce had great flavor and it was a pleasant visit",
    "thanks again yall that was fast",
    "the lobby was cool and comfortable and it felt like a smooth visit",
    "left with extra napkins and utensils without asking",
    "the pickup was smooth fr",
    "The dining area stayed tidy and it was a pleasant visit",
    "Counter staff were nice and the pace stayed steady",
    "Staff were welcoming and the pace stayed steady",
    "very freindly staff and everything came out right",
    "they got my extra sauce request right",
    "They made my order without any confusion and everything came out right",
    "nice to see drive thru was quick and easy and it made the stop easy.",
    "appreciate yall keeping it quick",
    "the staff asked if i needed anything else and it felt like a smooth visit.",
    "The sides were hot and fresh and the service stayed friendly",
    "the food stayed warm even after a few errands.",
    "yall were on it fr",
    "thanks yall for the quick bagging",
    "lobby smelled clean and the tables were wiped down",
    "they were on it and it was fast",
    "crowded night but my food still came out hot",
    "happy with how counter service was quick today and it was a pleasant visit",
    "Food was fresh and everything came out right",
    "Food was cooked good and it felt easy from start to finish.",
    "Chicken was hot and fresh and the pace stayed steady",
    "Staff were friendly today and the pace stayed steady.",
    "the staff was cool and helpful",
    "that was a smooth pickup for sure",
    "no cap yall were fast",
    "The breading stayed crunchy and everything came out right",
    "Nice to see the drive thru speaker was clear and the pace stayed steady",
    "the lemonade was cold and refreshing",
    "Great food and friendly employees and the team stayed organized",
    "the bone in chicken was juicy and it felt like a smooth visit",
    "that hit fr",
    "I noticed the chicken was not dry and the food was hot when i got it",
    "drove through and the speaker was clear and easy to hear.",
    "the lobby was cool and comfortable after being outside",
    "The line looked long but moved fast and everything came out right",
    "the speaker volume was good and i could hear clearly",
    "Chicken was crispy and hot and the staff kept things moving.",
    "Order was right and it felt easy from start to finish",
    "alexander checked the lobby and kept it tidy",
    "Staff were patient and everything came out right",
    "Quick stop and go and it felt easy from start to finish",
    "Good to see the drive thru order was read back correctly and everything came out right.",
    "Order was done quick and everything came out right.",
    "really liked that drive thru was quick n easy and the staff kept things moving.",
    "The dine in area was comfortable and it was a pleasant visit",
    "friendly ppl and it felt like a smooth visit",
    "the lobby was full but the tables were still clean",
    "thanks yall for keeping it quick",
    "The bag was packed securely and it felt easy from start to finish",
    "came in after work and the counter line was quick",
    "Freshly made and it felt easy from start to finish.",
    "that meal was gas and still hot",
    "the staff worked well even with a full lobby",
    "Nice to see counter staff were polite and the food was hot when i got it.",
    "the line was long but yall flew through it",
    "the sandwich bun was fresh and soft and it felt like a smooth visit",
    "Everyone was nice and it felt easy from start to finish",
    "the coleslaw was crisp and fresh",
    "Napkins and sauces were included without asking and everything came out right",
    "Glad to see drive thru order was right and the staff kept things moving",
    "Really tasty and it was a pleasant visit",
    "mobile pickup spot was clearly marked out front",
    "I noticed drive thru staff were nice and the pace stayed steady.",
    "Mac and cheese was good and the service stayed friendly",
    "solid visit and the food was fresh",
    "the line looked rough but it moved smooth",
    "that biscuit slapped",
    "Everything was fine today and the staff kept things moving",
    "the staff was real polite and helpful",
    "lowkey a great visit",
    "good looks on the quick order",
    "i noticed dine in was clean and it made the stop easy.",
    "Everything tasted fresh and it felt easy from start to finish",
    "it was loud but they stayed polite and helpful",
    "vibes were calm and the order was right",
    "service was smooth and the food was good",
    "The staff wore clean uniforms and it made the stop easy",
    "the drive thru kept rolling",
    "glad to see drive thru staff were helpful and the pace stayed steady.",
    "the drive thru was clutch today",
    "the fries stayed hot on the ride back",
    "happy with how dine in was quick and it was a pleasant visit.",
    "The staff stayed calm during a rush and it made the stop easy",
    "appreciated that drive thru was moving quick and it felt like a smooth visit.",
    "The coleslaw was crisp and it felt easy from start to finish",
    "the crew helped a new worker and kept it smooth.",
    "change was counted correctly and it felt like a smooth visit",
    "yall made it easy and fast",
    "The drink was cold and refreshing and the staff kept things moving.",
    "henry was cool and helpful and the team stayed organized",
    "the staff kept the line moving efficiently and it felt like a smooth visit.",
    "Glad to see the chicken was perfectly seasoned and it made the stop easy",
    "Mac n cheese was good and it made the stop easy.",
    "they were quick even with a rush",
    "the order was bagged carefully and nothing was crushed.",
    "yall were friendly and on it",
    "Short line and it was a pleasant visit.",
    "The tenders were a great size and it made the stop easy.",
    "Service felt organized and efficient and the pace stayed steady",
    "the store was busy but the vibe stayed chill",
    "Michael checked the counter and kept it moving",
    "Henry made sure things stayed on track and the staff kept things moving.",
    "nice to see dine in was nice and the food was hot when i got it",
    "Sides were good and the pace stayed steady",
    "took my food to go and the bag stayed sturdy",
    "the staff was cool af",
    "They brought my order to the table and the staff kept things moving",
    "food was worth the price and it felt like a smooth visit.",
    "The mashed potatoes were smooth and it made the stop easy.",
    "the biscuit was fluffy and not dry",
    "Alexander helped the crew and kept things smooth today",
    "fast service and good vibes",
    "the bag was sealed and everything was easy to carry.",
    "Glad to see the sandwich was not squished and the food was hot when i got it.",
    "trash bins were not overflowing in the dining room.",
    "they remembered my no pickle request",
    "came in with a stroller and they made space for us",
    "the staff smiled and said have a good day",
    "staff was freindly and the service stayed friendly",
    "restaurant was clean and tidy and the food was hot when i got it",
    "the meal tasted fresh and made to order",
    "Tables were arranged nicely and the pace stayed steady",
    "The mac and cheese was rich and the staff kept things moving",
    "The food temperature was perfect and the service stayed friendly.",
    "The drive thru was efficient and organized and it felt easy from start to finish",
    "saw the manager checking on the lobby while i waited",
    "food was gas and came out fast",
    "picked up on my way home and the drive thru was smooth",
    "Michael handled a busy rush without stress and it was a pleasant visit",
    "the food was gas and fresh",
    "Henry checked in and kept the pace steady and everything came out right",
    "The dipping sauce paired well and the pace stayed steady",
    "lowkey the food was fire",
    "the order was right and thats a W",
    "that was a W for sure",
    "that meal hit and i was out",
    "they kept the line moving even with a big order ahead",
    "michael jumped in and helped the crew and the food was hot when i got it.",
    "the store was easy to spot from the road",
    "The gloves were used properly and the team stayed organized",
    "Nice to see the meal was packaged neatly and everything came out right",
    "yall made my day with that fast service",
    "The counter staff were attentive and the staff kept things moving.",
    "got my food quick and the staff kept things moving.",
    "the parking lot lighting felt safe at night",
    "the sauce tasted fresh and paired well",
    "The order screen was accurate and the team stayed organized",
    "Alexandar was real nice and polite and the pace stayed steady",
    "the chicken was bussin",
    "good looks on the extra sauce",
    "good stop and it was a pleasant visit.",
    "sandwich was hot and fresh and it felt like a smooth visit",
    "that sandwich slapped and was fresh",
    "the staff said bye and have a good one",
    "rush was heavy but they didnt miss a thing",
    "Everyone seemed focused and helpful and it was a pleasant visit",
    "The chicken strips were tender and moist and the service stayed friendly",
    "the pickup shelf area was neat and uncluttered",
    "counter area looked tidy and well kept",
    "the sides tasted fresh and came out hot",
    "friendly crew and the food was hot when i got it",
    "The spicy sandwich had a great kick and it felt easy from start to finish.",
    "The rice was not dry and the staff kept things moving",
    "i noticed drive thru order was right and the team stayed organized",
    "chicken was super good and the food was hot when i got it.",
    "the sandwich was hot all the way through",
    "food came out quick and it made the stop easy",
    "counter line was short and the staff kept things moving",
    "Staff kept things moving and the service stayed friendly",
    "The food tasted better than expected and the team stayed organized",
    "The cashier explained the menu well and it made the stop easy",
    "yall made it easy for real",
    "was good today and the team stayed organized",
    "The store was spotless and it made the stop easy",
    "brought the kids and the staff were patient and kind",
    "yall were clutch today",
    "the pickup shelf had my name spelled right",
    "micheal checked on our order and smiled and it was a pleasant visit",
    "henry was attentive and helped the crew",
    "The service felt professional and the pace stayed steady",
    "Alexandar checked the lobby and said hi and the service stayed friendly",
    "Pickup was easy and the pace stayed steady.",
    "grabbed food before a movie and it was right on time",
    "No issues today and everything came out right",
    "Henry helped bag orders for a bit and it was a pleasant visit",
    "the staff kept the counter clean and it felt like a smooth visit",
    "lowkey the best visit ive had here",
    "The sandwich was assembled neatly and everything came out right.",
    "The mac and cheese was creamy and the pace stayed steady.",
    "alexander was helpful and chill and the team stayed organized.",
    "Food was hot and fresh and it felt easy from start to finish.",
    "good energy from the staff",
    "no cap this was a smooth visit",
    "picked up food for the family and everything was packed right",
    "Crew was helpful and the service stayed friendly",
    "Fast service and it made the stop easy",
    "no complaints and the food was hot when i got it",
    "Chicken sandwich was great and the pace stayed steady",
    "good vibes and a quick pickup",
    "the pickup shelf was easy and quick",
    "the drive thru menu board was easy to read",
    "manager michael made the visit easy and quick",
    "picked up for coworkers and the order was right",
    "food was delish and the pace stayed steady.",
    "Counter line moved fast and the service stayed friendly",
    "i noticed drive thru was smooth and it made the stop easy",
    "The store was easy to get in and out of and it felt easy from start to finish",
    "Pickup order ready on time and the pace stayed steady",
    "the breading stayed on the chicken and the food was hot when i got it",
    "the pickup parking spot was close to the door",
    "the cajun seasoning was flavorful and the food was hot when i got it",
    "Nice to see the order was ready right on time and the service stayed friendly",
    "The manager was visible and helpful and the pace stayed steady",
    "The dining room lights were bright and the team stayed organized",
    "The app order matched exactly and the staff kept things moving",
    "The sweet tea was perfect and the pace stayed steady",
    "Service was great and it was a pleasant visit",
    "they gave me extra sauce and it made the meal better",
    "yall were cool and helpful fr",
    "they wiped my table before i sat down",
    "grabbed a quick bite before practice and it was on time.",
    "the store was jumping but they kept it clean",
    "quick af and the order was right",
    "bathroom was stocked and looked clean",
    "Kind staff and the staff kept things moving",
    "the window staff were friendly and kept it moving",
    "Alexander kept the rush calm and the line moving for sure",
    "Drive thru staff were friendly and everything came out right.",
    "i noticed drive thru was fast and the team stayed organized",
    "Tables were wiped down quickly and it felt easy from start to finish",
    "The utensils were included and everything came out right",
    "They followed my no pickles request and it was a pleasant visit.",
    "no problems at all and the food was hot when i got it.",
    "The biscuit was fluffy inside and the pace stayed steady",
    "no cap the line moved fast",
    "Everything was exactly as requested and it made the stop easy.",
    "busy hour but they still got my order out fast",
    "the biscuit had a golden crust and it felt like a smooth visit",
    "The mild chicken still had flavor and it felt easy from start to finish.",
    "The sandwich wrapper was clean and neat and the team stayed organized.",
    "I noticed the fries were not oily and the service stayed friendly",
    "no wait at all and the food was hot when i got it",
    "The batter was crispy without being greasy and it felt easy from start to finish",
    "the food was fire af",
    "The food tasted like it was made to order and it was a pleasant visit.",
    "order was right and it made the stop easy",
    "My receipt was accurate and the pace stayed steady",
    "the lobby was cool and comfortable on a hot day.",
    "even with a big order ahead, they were quick",
    "Food was ready when I arrived and the service stayed friendly.",
    "pickup was smooth and everything came out right",
    "the sandwich bun was soft and held up well",
    "Nice to see the chicken was cooked evenly and everything came out right",
    "the biscuits were warm when i opened the bag",
    "i noticed food was hot n fresh and everything came out right",
    "Henry was present and made the visit easy and the service stayed friendly",
    "The bun held together well and the team stayed organized",
    "nice to see food was hot and tasy and everything came out right.",
    "The counter visit was fast and easy and the pace stayed steady.",
    "the lobby stayed chill even with people in it",
    "Nice stop and everything came out right.",
    "The counter area was organized and it felt easy from start to finish",
    "nice to see drive thru staff were friendly and the staff kept things moving.",
    "the meal was legit af",
    "they separated my kids meal from the spicy food",
    "Counter was easy today and it made the stop easy",
    "Food was packed well and everything came out right",
    "the chicken was cooked just right and the food was hot when i got it.",
    "real quick stop and no stress",
    "everything was straight and easy",
    "real chill vibes in the lobby",
    "Alexander made the visit feel smooth and it made the stop easy",
    "the crew was clutch during the rush",
    "Spicy sandwich hit the spot and the service stayed friendly",
    "the meal was hot and came out right",
    "glad to see the dine in service was quick and friendly and the pace stayed steady.",
    "Tasted great and it felt easy from start to finish.",
    "The crew thanked me at the window and the pace stayed steady",
    "Good to see drive thru was smooth today and everything came out right.",
    "Michael was friendly, not rushed and the service stayed friendly",
    "this spot stays consistent fr",
    "i noticed the drive thru line moved steadily and it was a pleasant visit.",
    "The meal felt freshly made and the service stayed friendly.",
    "The crew worked well as a team and it made the stop easy",
    "Trash bins were not overflowing and the service stayed friendly",
    "Tomatoes looked fresh and bright and it made the stop easy",
    "ordered for a group and they kept it organized",
    "michael was super chill today and it made the stop easy",
    "The staff helped a customer ahead of me kindly",
    "the staff asked if i needed anything else before i left.",
    "the front door and windows looked clean",
    "The pickup process was smooth and quick and the service stayed friendly",
    "glad to see dine in was quick today and the pace stayed steady",
    "the order number was called loud and clear",
    "counter was crowded but service was smooth",
    "Chicken was flavorful and the staff kept things moving.",
    "the lobby vibe was chill",
    "glad to see drive thru was quick and the service stayed friendly",
    "Fries were hot and it made the stop easy.",
    "yall were clutch with the sauces",
    "the drive thru lane was clean and moved steady",
    "drive thru moved fast even with a long line",
    "wait looked long but it went faster than normal",
    "Dine in tables were clean and the service stayed friendly.",
    "The batter had good flavor and the service stayed friendly",
    "the line moved fast and thats a W",
    "The dining room was comfortable and the staff kept things moving",
    "I noticed the order was assembled carefully and the food was hot when i got it",
    "My payment was quick and easy and it was a pleasant visit",
    "Happy with how the drive thru window service was quick and the staff kept things moving",
    "the order number was called promptly and the food was hot when i got it.",
    "sat by the window and it was quiet and comfy",
    "Would come again and the team stayed organized",
    "the kitchen was slammed but the order was right",
    "Great taste and everything came out right",
    "the food was gas no lie",
    "no cap the order was right",
    "real chill vibes in here",
    "appreciate the smooth drive thru",
    "They acknowledged me right away and the service stayed friendly",
    "the sandwich held together and wasnt messy.",
    "Pickup was ready when i got there and it made the stop easy",
    "Sandwich was tasty and it was a pleasant visit.",
    "Pickup staff were friendly and it was a pleasant visit",
    "The crust stayed crispy on the drive home and everything came out right",
    "Really liked the crispy chicken and everything came out right",
    "quick service and it felt like a smooth visit",
    "alexander was professional but warm and it felt like a smooth visit",
    "good vibes at the counter today",
    "the pickup shelf was easy to find and organized",
    "Henry was out front and helping out and it felt easy from start to finish",
    "Happy with how drive thru was fast n easy and the food was hot when i got it.",
    "The drink lid was secure and it was a pleasant visit",
    "food was greatt and it felt easy from start to finish",
    "line was long but it moved quicker than i expected",
    "order came fast and the team stayed organized.",
    "stopped in after a long day and the staff still had good energy",
    "Food was tasy and it felt easy from start to finish",
    "Drive thru line moved fast and the team stayed organized.",
    "Cashier was nice and the team stayed organized",
    "The manager thanked me personally and it felt easy from start to finish",
    "they called my number clearly and i heard it.",
    "The line for pickup was clear and everything came out right",
    "no cap the service was quick",
    "nice dinner and it felt like a smooth visit.",
    "The nuggets were crisp and the staff kept things moving",
    "the chicken was cooked evenly and tasted great",
    "The storefront windows were clean and it made the stop easy",
    "Food was warm and the pace stayed steady.",
    "The food quality was consistent and everything came out right",
    "the crew was on point fr",
    "they repeated my order and got it perfect",
    "solid service and good vibes",
    "Michael was easy to talk to and chill and the service stayed friendly",
    "the fries were hot and not soggy",
    "The store smelled like fresh food and it made the stop easy",
    "that was a W stop for sure",
    "long line but the staff kept it moving steady",
    "Food was still hot when I got home and it was a pleasant visit",
    "Staff handled the lunch rush smoothly and the service stayed friendly.",
    "The fryer oil tasted fresh, not old and it was a pleasant visit.",
    "the staff held the door for me which was nice",
    "The bag had all items listed and it made the stop easy",
    "ice was plentiful and clean and it felt like a smooth visit",
    "appreciated that the drive thru staff sounded cheerful and it felt like a smooth visit.",
    "the sandwich was fire no cap",
    "i noticed the meal was satisfying and hearty and it was a pleasant visit.",
    "food was good n hot and the pace stayed steady",
    "michael made sure my bag was right and the pace stayed steady.",
    "they offered extra sauce and i appreciated it.",
    "Drive thru was easy and it was a pleasant visit",
    "They got my order right and the pace stayed steady.",
    "they were short staffed but service was still solid",
    "the crew was chill and helpful",
    "the counter was busy but they kept it smooth",
    "Quick service and good food and it made the stop easy.",
    "the counter staff smiled and kept it friendly.",
    "appreciated that dine in was chill and it felt easy from start to finish.",
    "pickup was fast n easy and it felt like a smooth visit.",
    "the food smelled great in the car on the way home",
    "happy with how food was hot n tasty and it felt easy from start to finish.",
    "the sandwich stayed crispy even after the drive",
    "Henry stayed calm and kept the rush smooth",
    "The spicy chicken had real heat and the team stayed organized",
    "I noticed the dine in seating was comfortable and it felt like a smooth visit",
    "Service was quick and polite and the staff kept things moving.",
    "manager michale was cool and helpful and it felt like a smooth visit",
    "henry double checked the order screen and the food was hot when i got it.",
    "the breading stayed crispy and wasnt greasy",
    "lowkey a fast stop",
    "came in during the rain and they were still fast",
    "The lobby music was pleasant and the staff kept things moving",
    "the pickup sign was easy to see and the food was hot when i got it.",
    "grabbed a late dinner and the lobby was calm",
    "they split the order into two bags for easier carry",
    "Good visit and the service stayed friendly",
    "the meal was fire and hot",
    "Service was fast and everything came out right.",
    "drive thru order was accurate and the food was hot when i got it.",
    "the cashier was friendly and made it easy",
    "Thanks to Henry, everything felt organized and it made the stop easy",
    "shoutout to Michael for keeping the line moving",
    "got extra napkins without asking which was nice",
    "drive thru was quick no cap",
    "The combo was a good value and the staff kept things moving",
    "The kitchen looked organized and it was a pleasant visit",
    "the biscuits were warm and buttery inside",
    "red beans and rice were good and it felt like a smooth visit.",
    "fast service and the food was gas",
    "Glad to see the drive thru staff were upbeat and the food was hot when i got it.",
    "The biscuits were really good and it was a pleasant visit.",
    "The food hit the spot and the staff kept things moving",
    "Good meal and it made the stop easy",
    "Food was made fresh and the team stayed organized",
    "Coleslaw was good and it was a pleasant visit.",
    "glad to see the fries were seasoned just right and the team stayed organized.",
    "Got my food quick in the drive thru and it felt easy from start to finish",
    "that was a clean and quick visit",
    "quick visit and the food was hot when i got it",
    "the sauce options were tasty and the food was hot when i got it.",
    "the condiment area was clean and easy to use",
    "solid stop and the food was hot",
    "Alexander was out front helping and stayed polite",
    "Dine in staff were helpful and it was a pleasant visit",
    "Nice staff and good food and the team stayed organized",
    "Micheal was very kind and helpfull and the pace stayed steady",
    "the bag had all the sauces and utensils i needed",
    "Michael and the crew worked great together and the team stayed organized",
    "Great meal and the team stayed organized",
    "Great service in the drive thru and it made the stop easy.",
    "food was tasty and the food was hot when i got it.",
    "the mac and cheese was creamy and rich",
    "The staff repeated my order to confirm and it made the stop easy",
    "chicken had a nice crunch and it felt like a smooth visit.",
    "the sweet tea was just right",
    "My order was double checked and correct and it was a pleasant visit",
    "The soda tasted fresh and it was a pleasant visit",
    "Drive thru had no wait and it made the stop easy",
    "Michael was on top of the shift today and it made the stop easy.",
    "everythin was good and everything came out right.",
    "The pickup shelf was organized and the service stayed friendly",
    "the drive thru was smooth fr",
    "No missing items in the bag and the team stayed organized",
    "staff seemed swamped but still smiled",
    "staff were cool and it felt easy from start to finish.",
    "the team was chill and quick",
    "good spice level and the food was hot when i got it",
    "the rice and beans were cooked just right",
    "the meal was hot and tasted fresh and the food was hot when i got it",
    "that was a solid W",
    "the box was sealed well and the food was hot when i got it",
    "super clutch with the quick pickup",
    "The team handled a special request perfectly and it felt easy from start to finish",
    "Good portion sizes for the price and the staff kept things moving.",
    "The team greeted me with a smile and the staff kept things moving.",
    "the chicken tasted fresh and was still hot",
    "Clean dining room and the pace stayed steady.",
    "I noticed counter staff were helpful and the pace stayed steady.",
    "really good food and it felt like a smooth visit",
    "nice to see counter service was great and it made the stop easy",
    "good looks on the fresh food",
    "Solid meal and it was a pleasant visit",
    "appreciated how fast the service was and it felt like a smooth visit",
    "service was fast af",
    "the dining room chairs were clean and comfy",
    "yall kept it moving even with the rush",
    "Order taker was polite and the staff kept things moving",
    "Dine in was clean and comfy and the staff kept things moving.",
    "the floor was dry and not slippery",
    "The staff answered my question patiently and the team stayed organized.",
    "the food was bussin and hot",
    "they packed everything so it didnt spill",
    "this stop was a W",
    "Drive-thru moved quickly and the pace stayed steady.",
    "service was awsome and it made the stop easy.",
    "counter order was right and the food was hot when i got it.",
    "Cajun fries were good and it made the stop easy",
    "the dining room felt cozy and clean",
    "Bun was soft and the staff kept things moving.",
    "nice place and it felt like a smooth visit",
    "the meal was legit and hot",
    "Biscuits were flaky and the team stayed organized",
    "appreciate yall being so quick",
    "the crew was upbeat today and it felt like a smooth visit",
    "Good customer service and it felt easy from start to finish",
    "The experience was smooth from start to finish",
    "no cap that sandwich was fresh"
  ]
};
